$axure.loadCurrentPage({
  "url":"角色管理.html",
  "generationDate":new Date(1413021324480.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2a8193f402a948e9abba7057fc761abf",
    "type":"Axure:Page",
    "name":"角色管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c1666168c94e3baf1d3bfe07423490",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":970,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff627f7127eb4afb87ab2df30c85a1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":970,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u0.png"}},
{
          "id":"b46407a373914665b508a311f364fb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":0,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8abc925174c41dd8fd6f814e411cff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":0,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"0252a9a268be4ef2818280d0717b9ce9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":100,
              "y":67},
            "size":{
              "width":768,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a4cecc964043958d90ac80512dff73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":100,
                  "y":67},
                "size":{
                  "width":768,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u4.png"}},
{
          "id":"f511c452d4a14dffbe4c0847eddf625d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":868,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e3c5790d0b42c0b001030fb1957b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":868,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"89525d7147e54c5dbc646879351c7966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":608},
            "size":{
              "width":970,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2003e953eaab478b9d8d70ab743a5247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":608},
                "size":{
                  "width":970,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u36.png"}},
{
          "id":"aad78a3a8e8741a2939eafbd5b257208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":970,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1154c207ed6a488f9598b2fdb9b72373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":617},
                "size":{
                  "width":970,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u38.png"}},
{
          "id":"3f7f4fb5082e4988811fc8b4a23851c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c88e13368e84bbcbed34b0efc9ddd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c7304ef9d684a2d90cc3f056fa5248c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae9760916f9424c9917598b067074c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed860859a0a24b1e8f1161c8d549cc71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":444,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86996885e3445d58c07b06256ea0921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":444,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca4e3badb92405b8f60f4698388bce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":600,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc5b73c08db441da45be3fdff6e5471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":600,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2cb1543b524828987bf2d62d9e9caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":180,
              "y":670},
            "size":{
              "width":730,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c8fce9811948daa0f207789af7475e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":670},
                "size":{
                  "width":730,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c998ed93cbb64e23a970f3ea6ea88915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":105},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f37dd473e0449538fb2674829e2b35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":105},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cacdd89a528344dfa8058ef91bd846d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":130},
            "size":{
              "width":92,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3ec3da4c834fc4adba428959365fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":130},
                "size":{
                  "width":92,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5daf66c73ff4b5b88fb4161a1b6009d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":138,
              "y":153},
            "size":{
              "width":80,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffb3eb8450d4d33b53b35c5f5425974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":153},
                "size":{
                  "width":80,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b57edcd60cdb45808ac39c133eef85de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":177},
            "size":{
              "width":92,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c3bc78b6284cbd806cc9f40debb658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":177},
                "size":{
                  "width":92,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"988bbc16994f43a5a9801c799d12121d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":197},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3db4d053277d4950adc7ecca54e454b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":197},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0742472d40b43a78616f2972fe10445",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":317},
            "size":{
              "width":100,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58ee195d49a4fe1affb4c99fbe76cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":317},
                "size":{
                  "width":100,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55670c3c879e402b9defb2f9718d7b3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":222},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f882ca2105544b79f4614407b048b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":222},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37069e75f62d4975809b8b5da958c81b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":338},
            "size":{
              "width":89,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d75a4364bc44d29b6c83546c9643e83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":338},
                "size":{
                  "width":89,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8cd8faf6724455997eeaf176f45bee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":357},
            "size":{
              "width":109,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36eabcf220854d078eac8bccdbf4ffe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":357},
                "size":{
                  "width":109,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2211a83d1534baaa8e053af23d21052",
          "label":"tab1",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":140},
            "size":{
              "width":317,
              "height":169}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b5e43817d714f8eb9781faef210a3e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":67,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83b1c2c2ce6546a4baa39aded9ac3c60",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":67,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u49.png"}},
{
              "id":"5733d1d38bee4276a819a95bce3162f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":62},
                "size":{
                  "width":67,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f208f0aa73b543cd96cf6f448ac9130b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":67,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u57.png"}},
{
              "id":"d4357b82f6f448088615c407faabdd9a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":67,
                  "y":36},
                "size":{
                  "width":66,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6269c44ddfb64900bd15f52466a0c06a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":67,
                      "y":36},
                    "size":{
                      "width":66,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u51.png"}},
{
              "id":"175bbbd6c7524b49b60dedf09af6e5b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":67,
                  "y":62},
                "size":{
                  "width":66,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dba3dd1ca52748599bebfe8305bc3caf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":67,
                      "y":62},
                    "size":{
                      "width":66,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u59.png"}},
{
              "id":"3925678763b147489cfb1afb501291de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":67,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb5112d239074a3c9f5f8270751df905",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":67,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u57.png"}},
{
              "id":"052e830b10d74c3f8c2f9866eb537390",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":67,
                  "y":90},
                "size":{
                  "width":66,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8289a83c00cc46fb8f43c0742ad653b6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":67,
                      "y":90},
                    "size":{
                      "width":66,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u59.png"}},
{
              "id":"4ca98a4950be463a9cacf691701977e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":118},
                "size":{
                  "width":67,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f95852dddad04422a99a133391225546",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":118},
                    "size":{
                      "width":67,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u73.png"}},
{
              "id":"2b330064ce1a4dd29b9d2724358d0336",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":67,
                  "y":118},
                "size":{
                  "width":66,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b93e3da94a52419e979207741bd9f9e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":67,
                      "y":118},
                    "size":{
                      "width":66,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u75.png"}},
{
              "id":"289f35d39dfc4384807c5ff2a0ee916e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":36},
                "size":{
                  "width":100,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d6d56d4d91c64c42b10a8d1ab20430f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF23BEB1,
                      "opacity":1},
                    "location":{
                      "x":217,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"fadeWidget",
                          "description":"显示/隐藏部件",
                          "objectsToFades":[]}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/角色管理/u55.png"}},
{
              "id":"19f8ea63d3814c3487ac153807d91dfe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":62},
                "size":{
                  "width":100,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29810fa693c24d0e97835148bb0fbd80",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF23BEB1,
                      "opacity":1},
                    "location":{
                      "x":217,
                      "y":62},
                    "size":{
                      "width":100,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u63.png"}},
{
              "id":"6f5ad0f41ee24b91b325a598e0b38dff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":90},
                "size":{
                  "width":100,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ca5679c0f4649a5aa6192bf54ec62c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF23BEB1,
                      "opacity":1},
                    "location":{
                      "x":217,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u63.png"}},
{
              "id":"60fe28f8fd3743dd89b3a1d953a42dd5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":118},
                "size":{
                  "width":100,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f44f995eaf24a3eb8301176d1602676",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF23BEB1,
                      "opacity":1},
                    "location":{
                      "x":217,
                      "y":118},
                    "size":{
                      "width":100,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u79.png"}},
{
              "id":"77a65a0f343e4046a52bb111f54cbbd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":67,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cd3b4f1d918d4737bff65c340afe21dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":67,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u41.png"}},
{
              "id":"e82e0eb30cd245559edef27da1e4e570",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":67,
                  "y":0},
                "size":{
                  "width":66,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc931d1b2547468891728676cf66e335",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":67,
                      "y":0},
                    "size":{
                      "width":66,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u43.png"}},
{
              "id":"19bfdc134bb04b008f56abef50c381bb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":217,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae570de0e8d24e59a1fa65935f91e3ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":217,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u47.png"}},
{
              "id":"3897f9979d064658b64091662cd5f257",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":133,
                  "y":0},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8d95371ee654ab5a7857a190e55af29",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":133,
                      "y":0},
                    "size":{
                      "width":84,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u45.png"}},
{
              "id":"d88fc00d72644475a04140e369f21568",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":133,
                  "y":36},
                "size":{
                  "width":84,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4611239487f7417d8727ff429f65d7ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":133,
                      "y":36},
                    "size":{
                      "width":84,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u53.png"}},
{
              "id":"cf22b6620a2e4c35854191696128c850",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":133,
                  "y":62},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"11f71a0005074c389fd287352833dda9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":133,
                      "y":62},
                    "size":{
                      "width":84,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u61.png"}},
{
              "id":"99ca70498bf64b72a0e9bacdb7276747",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":133,
                  "y":90},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"42c6792c777147a7ac55a5dcb3d72206",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":133,
                      "y":90},
                    "size":{
                      "width":84,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u61.png"}},
{
              "id":"e9ae0c72efca432591fdb00d14a0527c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":133,
                  "y":118},
                "size":{
                  "width":84,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5db865dc994f4ddb97eb86a34c21720a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":133,
                      "y":118},
                    "size":{
                      "width":84,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u77.png"}},
{
              "id":"fd21594be54c4e7b87b75c9b2424bb9a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":67,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0adc3ade288b4f8d92626f292ff0a75d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":67,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u81.png"}},
{
              "id":"971ad4ce253b4386b5ac371ed173271e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":67,
                  "y":140},
                "size":{
                  "width":66,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6aa5b09dded490bb6319f74c758405e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":67,
                      "y":140},
                    "size":{
                      "width":66,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u83.png"}},
{
              "id":"74dfce6734ae43f498eab97346e811ba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":133,
                  "y":140},
                "size":{
                  "width":84,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"13e0d6c0910a48f9a616d60ca9406d7a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":133,
                      "y":140},
                    "size":{
                      "width":84,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u85.png"}},
{
              "id":"ec1e2f0847e1488fa35d8edea6390cb2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":140},
                "size":{
                  "width":100,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c580966ce49e4da29d880d2ee02529a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF23BEB1,
                      "opacity":1},
                    "location":{
                      "x":217,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u87.png"}}]},
{
          "id":"ea1634e02c9b42919e9bff33d74955bd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":98},
            "size":{
              "width":564,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/财务数据/u54_line.png"}},
{
          "id":"6d3180de770c444980c6075755cc3fe3",
          "label":"b1",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":263,
              "y":79},
            "size":{
              "width":124,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"416d32e8ef72472392c21397d4a3c49d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":263,
                  "y":79},
                "size":{
                  "width":124,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工单登记/b1_u133.png",
            "selected~":"images/工单登记/b1_u133_selected.png"}},
{
          "id":"d299cabdf1fc46cf970a95e857dd6735",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":242},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0379f2ef86bf432b9ca904c0b307234f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":242},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2bdd0e68cca4621b7ae206ae042202a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":261},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe427b26eeac47bbbd72f011660c1976",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":261},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1722d4c0f65a4fc0a1b5b3948423d4ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":279},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3792dd5ab13342eba4c8a29e9a29e4e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":279},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"254117c7fc7a4aebb8314d964a7f25fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":299},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcb13886834a47e5b87d41f9b1d02371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":299},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"992dc994cf6a42ec8bc42864f9ca7722",
          "label":"Date Field From",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":271,
              "y":282},
            "size":{
              "width":56,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7542e0a594ce4d6c985a13475f03618d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC00},
            "location":{
              "x":263,
              "y":106},
            "size":{
              "width":70,
              "height":24},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4009e287c7f443c59adf760c3ac901b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00},
                "location":{
                  "x":263,
                  "y":106},
                "size":{
                  "width":70,
                  "height":24},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/景点设置/u70.png"}},
{
          "id":"d86ad9c738134b27b1b155921713ff4f",
          "label":"Date Field From",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":337,
              "y":282},
            "size":{
              "width":56,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5c0e58de2ad94aa98224332088e0dc63",
          "label":"tab1",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":140},
            "size":{
              "width":210,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a53ae724d16450c9c0639033c3c7a77",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":210,
                  "height":410}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e08e373d02c444d2bd1488f8f09c71cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":210,
                      "height":410}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u105.png"}}]},
{
          "id":"3a716e7c84e546a1bce13b812142114b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":630,
              "y":120},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a262dd3b223478bb4ef71f17422b702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":630,
                  "y":120},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae3c0aeaa45547a79b6e7c0012e6bfde",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":660,
              "y":169.5},
            "size":{
              "width":50,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"839e13a2ed104bfdb08a978177f81418",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":660,
                  "y":169.5},
                "size":{
                  "width":50,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/角色管理/u109.png"}},
{
          "id":"afcd81b5b3d24ae995b7d085ceeae68a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":164},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e7e968a480c4cecb30972d7e8bc38ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":164},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d4b49a2d552a4c30bd5aceed20604235",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":186},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21a6fe00e59e4b368c6174a51386f943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":186},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fbd9eb1ca5d54d898c60dbd0e94a548a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":698,
              "y":211},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"071e069448ae474db7dab1f94885b77a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698,
                  "y":211},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"69ac08b7093641e08e392ae95105d1cd",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":698,
              "y":237},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f76f197d6414ad1a0ab86f830024513",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698,
                  "y":237},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"eb6f25914a374212b9846ffb8e310a43",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":263},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6240431ea32c4e5c8eb4b3da5b47275a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":263},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4fee08744787440ebb82cc08d01b17fb",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":698,
              "y":287},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f6ade218aa449d8e7058241e98c50b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698,
                  "y":287},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0e1e03daf13d4f5f89b014d3ee76aba0",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":698,
              "y":313},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2115dff922f4064a12eecf86167b2b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698,
                  "y":313},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ae5ea86cd5474c76802c394c5f4b0290",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":337},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b419474aec7a4547a99bddddb70441ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":337},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"33bd1cad26a84081852845c15a6da8fc",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":363},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e56b25ec6b1948b5a546e998778da884",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":363},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"09ac641332c94acf8a59cf6865f5157c",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":387},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"498f956d811d49b0bf206c3576f74d9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":387},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4738fa557b2046458fd1ff061069ba56",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":413},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49767e7c73e94eb791faf4b6abb152dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":413},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"63c00fa636f84c7397cf93b2a01f4d85",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":439},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"356de5a01eaf4762912dfcfe17e9c2b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":439},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "03c1666168c94e3baf1d3bfe07423490":{
      "scriptId":"u0"},
    "ff627f7127eb4afb87ab2df30c85a1bd":{
      "scriptId":"u1"},
    "b46407a373914665b508a311f364fb8d":{
      "scriptId":"u2"},
    "d8abc925174c41dd8fd6f814e411cff5":{
      "scriptId":"u3"},
    "0252a9a268be4ef2818280d0717b9ce9":{
      "scriptId":"u4"},
    "e1a4cecc964043958d90ac80512dff73":{
      "scriptId":"u5"},
    "f511c452d4a14dffbe4c0847eddf625d":{
      "scriptId":"u6"},
    "e4e3c5790d0b42c0b001030fb1957b71":{
      "scriptId":"u7"},
    "89525d7147e54c5dbc646879351c7966":{
      "scriptId":"u8"},
    "2003e953eaab478b9d8d70ab743a5247":{
      "scriptId":"u9"},
    "aad78a3a8e8741a2939eafbd5b257208":{
      "scriptId":"u10"},
    "1154c207ed6a488f9598b2fdb9b72373":{
      "scriptId":"u11"},
    "3f7f4fb5082e4988811fc8b4a23851c4":{
      "scriptId":"u12"},
    "1c88e13368e84bbcbed34b0efc9ddd49":{
      "scriptId":"u13"},
    "1c7304ef9d684a2d90cc3f056fa5248c":{
      "scriptId":"u14"},
    "eae9760916f9424c9917598b067074c6":{
      "scriptId":"u15"},
    "ed860859a0a24b1e8f1161c8d549cc71":{
      "scriptId":"u16"},
    "b86996885e3445d58c07b06256ea0921":{
      "scriptId":"u17"},
    "8ca4e3badb92405b8f60f4698388bce7":{
      "scriptId":"u18"},
    "4bc5b73c08db441da45be3fdff6e5471":{
      "scriptId":"u19"},
    "4d2cb1543b524828987bf2d62d9e9caf":{
      "scriptId":"u20"},
    "e9c8fce9811948daa0f207789af7475e":{
      "scriptId":"u21"},
    "c998ed93cbb64e23a970f3ea6ea88915":{
      "scriptId":"u22"},
    "3f37dd473e0449538fb2674829e2b35f":{
      "scriptId":"u23"},
    "cacdd89a528344dfa8058ef91bd846d1":{
      "scriptId":"u24"},
    "7c3ec3da4c834fc4adba428959365fbb":{
      "scriptId":"u25"},
    "d5daf66c73ff4b5b88fb4161a1b6009d":{
      "scriptId":"u26"},
    "8ffb3eb8450d4d33b53b35c5f5425974":{
      "scriptId":"u27"},
    "b57edcd60cdb45808ac39c133eef85de":{
      "scriptId":"u28"},
    "43c3bc78b6284cbd806cc9f40debb658":{
      "scriptId":"u29"},
    "988bbc16994f43a5a9801c799d12121d":{
      "scriptId":"u30"},
    "3db4d053277d4950adc7ecca54e454b0":{
      "scriptId":"u31"},
    "c0742472d40b43a78616f2972fe10445":{
      "scriptId":"u32"},
    "d58ee195d49a4fe1affb4c99fbe76cf0":{
      "scriptId":"u33"},
    "55670c3c879e402b9defb2f9718d7b3c":{
      "scriptId":"u34"},
    "7f882ca2105544b79f4614407b048b05":{
      "scriptId":"u35"},
    "37069e75f62d4975809b8b5da958c81b":{
      "scriptId":"u36"},
    "3d75a4364bc44d29b6c83546c9643e83":{
      "scriptId":"u37"},
    "c8cd8faf6724455997eeaf176f45bee3":{
      "scriptId":"u38"},
    "36eabcf220854d078eac8bccdbf4ffe7":{
      "scriptId":"u39"},
    "c2211a83d1534baaa8e053af23d21052":{
      "scriptId":"u40"},
    "77a65a0f343e4046a52bb111f54cbbd8":{
      "scriptId":"u41"},
    "cd3b4f1d918d4737bff65c340afe21dc":{
      "scriptId":"u42"},
    "e82e0eb30cd245559edef27da1e4e570":{
      "scriptId":"u43"},
    "dc931d1b2547468891728676cf66e335":{
      "scriptId":"u44"},
    "3897f9979d064658b64091662cd5f257":{
      "scriptId":"u45"},
    "f8d95371ee654ab5a7857a190e55af29":{
      "scriptId":"u46"},
    "19bfdc134bb04b008f56abef50c381bb":{
      "scriptId":"u47"},
    "ae570de0e8d24e59a1fa65935f91e3ce":{
      "scriptId":"u48"},
    "1b5e43817d714f8eb9781faef210a3e3":{
      "scriptId":"u49"},
    "83b1c2c2ce6546a4baa39aded9ac3c60":{
      "scriptId":"u50"},
    "d4357b82f6f448088615c407faabdd9a":{
      "scriptId":"u51"},
    "6269c44ddfb64900bd15f52466a0c06a":{
      "scriptId":"u52"},
    "d88fc00d72644475a04140e369f21568":{
      "scriptId":"u53"},
    "4611239487f7417d8727ff429f65d7ee":{
      "scriptId":"u54"},
    "289f35d39dfc4384807c5ff2a0ee916e":{
      "scriptId":"u55"},
    "d6d56d4d91c64c42b10a8d1ab20430f9":{
      "scriptId":"u56"},
    "5733d1d38bee4276a819a95bce3162f7":{
      "scriptId":"u57"},
    "f208f0aa73b543cd96cf6f448ac9130b":{
      "scriptId":"u58"},
    "175bbbd6c7524b49b60dedf09af6e5b5":{
      "scriptId":"u59"},
    "dba3dd1ca52748599bebfe8305bc3caf":{
      "scriptId":"u60"},
    "cf22b6620a2e4c35854191696128c850":{
      "scriptId":"u61"},
    "11f71a0005074c389fd287352833dda9":{
      "scriptId":"u62"},
    "19f8ea63d3814c3487ac153807d91dfe":{
      "scriptId":"u63"},
    "29810fa693c24d0e97835148bb0fbd80":{
      "scriptId":"u64"},
    "3925678763b147489cfb1afb501291de":{
      "scriptId":"u65"},
    "fb5112d239074a3c9f5f8270751df905":{
      "scriptId":"u66"},
    "052e830b10d74c3f8c2f9866eb537390":{
      "scriptId":"u67"},
    "8289a83c00cc46fb8f43c0742ad653b6":{
      "scriptId":"u68"},
    "99ca70498bf64b72a0e9bacdb7276747":{
      "scriptId":"u69"},
    "42c6792c777147a7ac55a5dcb3d72206":{
      "scriptId":"u70"},
    "6f5ad0f41ee24b91b325a598e0b38dff":{
      "scriptId":"u71"},
    "2ca5679c0f4649a5aa6192bf54ec62c4":{
      "scriptId":"u72"},
    "4ca98a4950be463a9cacf691701977e6":{
      "scriptId":"u73"},
    "f95852dddad04422a99a133391225546":{
      "scriptId":"u74"},
    "2b330064ce1a4dd29b9d2724358d0336":{
      "scriptId":"u75"},
    "b93e3da94a52419e979207741bd9f9e5":{
      "scriptId":"u76"},
    "e9ae0c72efca432591fdb00d14a0527c":{
      "scriptId":"u77"},
    "5db865dc994f4ddb97eb86a34c21720a":{
      "scriptId":"u78"},
    "60fe28f8fd3743dd89b3a1d953a42dd5":{
      "scriptId":"u79"},
    "2f44f995eaf24a3eb8301176d1602676":{
      "scriptId":"u80"},
    "fd21594be54c4e7b87b75c9b2424bb9a":{
      "scriptId":"u81"},
    "0adc3ade288b4f8d92626f292ff0a75d":{
      "scriptId":"u82"},
    "971ad4ce253b4386b5ac371ed173271e":{
      "scriptId":"u83"},
    "c6aa5b09dded490bb6319f74c758405e":{
      "scriptId":"u84"},
    "74dfce6734ae43f498eab97346e811ba":{
      "scriptId":"u85"},
    "13e0d6c0910a48f9a616d60ca9406d7a":{
      "scriptId":"u86"},
    "ec1e2f0847e1488fa35d8edea6390cb2":{
      "scriptId":"u87"},
    "c580966ce49e4da29d880d2ee02529a4":{
      "scriptId":"u88"},
    "ea1634e02c9b42919e9bff33d74955bd":{
      "scriptId":"u89"},
    "6d3180de770c444980c6075755cc3fe3":{
      "scriptId":"u90"},
    "416d32e8ef72472392c21397d4a3c49d":{
      "scriptId":"u91"},
    "d299cabdf1fc46cf970a95e857dd6735":{
      "scriptId":"u92"},
    "0379f2ef86bf432b9ca904c0b307234f":{
      "scriptId":"u93"},
    "c2bdd0e68cca4621b7ae206ae042202a":{
      "scriptId":"u94"},
    "fe427b26eeac47bbbd72f011660c1976":{
      "scriptId":"u95"},
    "1722d4c0f65a4fc0a1b5b3948423d4ef":{
      "scriptId":"u96"},
    "3792dd5ab13342eba4c8a29e9a29e4e0":{
      "scriptId":"u97"},
    "254117c7fc7a4aebb8314d964a7f25fa":{
      "scriptId":"u98"},
    "bcb13886834a47e5b87d41f9b1d02371":{
      "scriptId":"u99"},
    "992dc994cf6a42ec8bc42864f9ca7722":{
      "scriptId":"u100"},
    "7542e0a594ce4d6c985a13475f03618d":{
      "scriptId":"u101"},
    "4009e287c7f443c59adf760c3ac901b3":{
      "scriptId":"u102"},
    "d86ad9c738134b27b1b155921713ff4f":{
      "scriptId":"u103"},
    "5c0e58de2ad94aa98224332088e0dc63":{
      "scriptId":"u104"},
    "7a53ae724d16450c9c0639033c3c7a77":{
      "scriptId":"u105"},
    "e08e373d02c444d2bd1488f8f09c71cf":{
      "scriptId":"u106"},
    "3a716e7c84e546a1bce13b812142114b":{
      "scriptId":"u107"},
    "4a262dd3b223478bb4ef71f17422b702":{
      "scriptId":"u108"},
    "ae3c0aeaa45547a79b6e7c0012e6bfde":{
      "scriptId":"u109"},
    "839e13a2ed104bfdb08a978177f81418":{
      "scriptId":"u110"},
    "afcd81b5b3d24ae995b7d085ceeae68a":{
      "scriptId":"u111"},
    "1e7e968a480c4cecb30972d7e8bc38ba":{
      "scriptId":"u112"},
    "d4b49a2d552a4c30bd5aceed20604235":{
      "scriptId":"u113"},
    "21a6fe00e59e4b368c6174a51386f943":{
      "scriptId":"u114"},
    "fbd9eb1ca5d54d898c60dbd0e94a548a":{
      "scriptId":"u115"},
    "071e069448ae474db7dab1f94885b77a":{
      "scriptId":"u116"},
    "69ac08b7093641e08e392ae95105d1cd":{
      "scriptId":"u117"},
    "2f76f197d6414ad1a0ab86f830024513":{
      "scriptId":"u118"},
    "eb6f25914a374212b9846ffb8e310a43":{
      "scriptId":"u119"},
    "6240431ea32c4e5c8eb4b3da5b47275a":{
      "scriptId":"u120"},
    "4fee08744787440ebb82cc08d01b17fb":{
      "scriptId":"u121"},
    "e7f6ade218aa449d8e7058241e98c50b":{
      "scriptId":"u122"},
    "0e1e03daf13d4f5f89b014d3ee76aba0":{
      "scriptId":"u123"},
    "d2115dff922f4064a12eecf86167b2b7":{
      "scriptId":"u124"},
    "ae5ea86cd5474c76802c394c5f4b0290":{
      "scriptId":"u125"},
    "b419474aec7a4547a99bddddb70441ab":{
      "scriptId":"u126"},
    "33bd1cad26a84081852845c15a6da8fc":{
      "scriptId":"u127"},
    "e56b25ec6b1948b5a546e998778da884":{
      "scriptId":"u128"},
    "09ac641332c94acf8a59cf6865f5157c":{
      "scriptId":"u129"},
    "498f956d811d49b0bf206c3576f74d9a":{
      "scriptId":"u130"},
    "4738fa557b2046458fd1ff061069ba56":{
      "scriptId":"u131"},
    "49767e7c73e94eb791faf4b6abb152dc":{
      "scriptId":"u132"},
    "63c00fa636f84c7397cf93b2a01f4d85":{
      "scriptId":"u133"},
    "356de5a01eaf4762912dfcfe17e9c2b2":{
      "scriptId":"u134"}}});