$axure.loadCurrentPage({
  "url":"满意度评价.html",
  "generationDate":new Date(1412907464504.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a42f3355e3c549c3964c888dc61ac29f",
    "type":"Axure:Page",
    "name":"满意度评价",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c1666168c94e3baf1d3bfe07423490",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":970,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff627f7127eb4afb87ab2df30c85a1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":970,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u10.png"}},
{
          "id":"b46407a373914665b508a311f364fb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":0,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8abc925174c41dd8fd6f814e411cff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":0,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"0252a9a268be4ef2818280d0717b9ce9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":100,
              "y":67},
            "size":{
              "width":768,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a4cecc964043958d90ac80512dff73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":100,
                  "y":67},
                "size":{
                  "width":768,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购券状态查询/u4.png"}},
{
          "id":"f511c452d4a14dffbe4c0847eddf625d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":868,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e3c5790d0b42c0b001030fb1957b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":868,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"89525d7147e54c5dbc646879351c7966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":608},
            "size":{
              "width":970,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2003e953eaab478b9d8d70ab743a5247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":608},
                "size":{
                  "width":970,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u36.png"}},
{
          "id":"aad78a3a8e8741a2939eafbd5b257208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":970,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1154c207ed6a488f9598b2fdb9b72373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":617},
                "size":{
                  "width":970,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u38.png"}},
{
          "id":"3f7f4fb5082e4988811fc8b4a23851c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c88e13368e84bbcbed34b0efc9ddd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c7304ef9d684a2d90cc3f056fa5248c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae9760916f9424c9917598b067074c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed860859a0a24b1e8f1161c8d549cc71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":444,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86996885e3445d58c07b06256ea0921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":444,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca4e3badb92405b8f60f4698388bce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":600,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc5b73c08db441da45be3fdff6e5471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":600,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2cb1543b524828987bf2d62d9e9caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":180,
              "y":670},
            "size":{
              "width":730,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c8fce9811948daa0f207789af7475e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":670},
                "size":{
                  "width":730,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c998ed93cbb64e23a970f3ea6ea88915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":105},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f37dd473e0449538fb2674829e2b35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":105},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cacdd89a528344dfa8058ef91bd846d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":130},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3ec3da4c834fc4adba428959365fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":130},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5daf66c73ff4b5b88fb4161a1b6009d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":156},
            "size":{
              "width":80,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffb3eb8450d4d33b53b35c5f5425974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":156},
                "size":{
                  "width":80,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f2060315414ec8943fe2e6b11dbc0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":181},
            "size":{
              "width":90,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d27c5e6343d0416f9a1ff24c5cd07755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":181},
                "size":{
                  "width":90,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b57edcd60cdb45808ac39c133eef85de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":205},
            "size":{
              "width":92,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c3bc78b6284cbd806cc9f40debb658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":205},
                "size":{
                  "width":92,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89b019dab1b04cadb3b9a519186fc70b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":231},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff2fccf858348e0892846d382b4a22b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":231},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd8eeff987774ec79e928768ccbd9cb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":255},
            "size":{
              "width":91,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"434de672b0bf44639eabacde8cfd3ab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":255},
                "size":{
                  "width":91,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2df02b8672f4ac39112063cb8770d13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":279},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d89ee1e4aaf748deba51d948bd82a93b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":279},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c186dca97f4419a8dc82135c8a06c87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":347},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d08114d29f43ef9c8270c8391d9375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":347},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"988bbc16994f43a5a9801c799d12121d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":373},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3db4d053277d4950adc7ecca54e454b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":373},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0742472d40b43a78616f2972fe10445",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":398},
            "size":{
              "width":100,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58ee195d49a4fe1affb4c99fbe76cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":398},
                "size":{
                  "width":100,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f7241f5d1bc4a95955fc632febeb8e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":265,
              "y":87},
            "size":{
              "width":234,
              "height":35},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c9a004d348a460e88fc57a4b0d081ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":265,
                  "y":87},
                "size":{
                  "width":234,
                  "height":35},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58b87410cbe6483d8d031161fb3059e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":492,
              "y":71},
            "size":{
              "width":323,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1650839b2614722b6dc5bbe3b3f8745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":492,
                  "y":71},
                "size":{
                  "width":323,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购券状态查询/u44.png"}},
{
          "id":"aa3eb74103134c5baffb4073886d6ae4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":509,
              "y":87},
            "size":{
              "width":259,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9efb951a56ca4035a5ef65b22050116c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":509,
                  "y":87},
                "size":{
                  "width":259,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6f1226af4ea44e48806b7d30249acaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":141,
              "y":302},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ce440aeb924762b6bb943b6514a486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":302},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26a57ef67c81421f98f42f4580afd175",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":324},
            "size":{
              "width":89,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58873b1d017c4ee4b8c8b0743853fa92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":324},
                "size":{
                  "width":89,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26eece99fd6d43aca84a3fa6260624e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":265,
              "y":139},
            "size":{
              "width":145,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa4020c55d64d4dac57f75ec1363af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":265,
                  "y":139},
                "size":{
                  "width":145,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c31e47c70814f12a81f70df5a98355d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":162},
            "size":{
              "width":570,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bcd03196da44191a81c489a83aa66e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":162},
                "size":{
                  "width":570,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u56.png"}},
{
          "id":"6c4e0f18015d42588fc3d21f1018dcaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":261,
              "y":300},
            "size":{
              "width":99,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"764b491f3ffe46fba8a92d8a077cd53c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":261,
                  "y":300},
                "size":{
                  "width":99,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u58.png"}},
{
          "id":"b06ae73baa04479cb9edde843695954c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":370,
              "y":300},
            "size":{
              "width":99,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1141047d8db47e28c185883d94bd5e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":370,
                  "y":300},
                "size":{
                  "width":99,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u60.png"}},
{
          "id":"8536000be5b34a3cbe4faaafe50591ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":485,
              "y":300},
            "size":{
              "width":99,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71f40a1ffdd040a89a507d1d8bf2846c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":485,
                  "y":300},
                "size":{
                  "width":99,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u60.png"}},
{
          "id":"0d674d6d07ce4c68a8889dacb7f42f6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":599,
              "y":300},
            "size":{
              "width":99,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3edbf1b74ede4a21be36f7456128dc33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":599,
                  "y":300},
                "size":{
                  "width":99,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u60.png"}},
{
          "id":"3366776b1d724963a3d787500dfb6d06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":713,
              "y":300},
            "size":{
              "width":99,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d25031a95946ed843ca7a49b434e0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":713,
                  "y":300},
                "size":{
                  "width":99,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u60.png"}},
{
          "id":"0c3cdaaa23e44549b47db71a98f20d65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":262,
              "y":333},
            "size":{
              "width":138,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4eaeab269994de0a6c587a754133fb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":262,
                  "y":333},
                "size":{
                  "width":138,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d144b30c80fc43a19b0a1a030f4a7f48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":724,
              "y":332},
            "size":{
              "width":76,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f1910b5fdf466987ac5fbeb2a8c12c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":724,
                  "y":332},
                "size":{
                  "width":76,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u70.png"}},
{
          "id":"15204e0792634ddfa39a23885715b888",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":262,
              "y":359},
            "size":{
              "width":538,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392a8c8a19214aea919d00eeedd6644e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":262,
                  "y":359},
                "size":{
                  "width":538,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b10f5ca9430748d2b3d725665a191c79",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":380},
            "size":{
              "width":550,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/满意度评价/u74_line.png"}},
{
          "id":"a1907a1dd4464350aefa8b33ad2bbc08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":742,
              "y":360},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2077ba1bccd74b85977a9ce731a1c076",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":742,
                  "y":360},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u75.png"}},
{
          "id":"b2d050f4dbdb4d6f9881d47e5fb52876",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":262,
              "y":391},
            "size":{
              "width":138,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c71c099c8a664dfabb407d9eca195ba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":262,
                  "y":391},
                "size":{
                  "width":138,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27689801a8ac437a8f034c60e9590177",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":724,
              "y":390},
            "size":{
              "width":76,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b0b9f62640c4f8184a10745548d8482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":724,
                  "y":390},
                "size":{
                  "width":76,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u70.png"}},
{
          "id":"c0b861cd1a7a43a5b0fe88b512c6557d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":262,
              "y":417},
            "size":{
              "width":538,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edc01c65b397435088b8cc45a753f68c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":262,
                  "y":417},
                "size":{
                  "width":538,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67423c7558aa40df92daf9cc0c41a3ae",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":438},
            "size":{
              "width":550,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/满意度评价/u74_line.png"}},
{
          "id":"69166b69627545eebe8c4006dc8c0691",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":262,
              "y":459},
            "size":{
              "width":138,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1711dba891d5479494c0447a921f2373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":262,
                  "y":459},
                "size":{
                  "width":138,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65cdf2ff46854db685fe0596fb56ff31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":724,
              "y":458},
            "size":{
              "width":76,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a8fb95baa6f49548ccd9133f67dccd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":724,
                  "y":458},
                "size":{
                  "width":76,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u70.png"}},
{
          "id":"ddad5c0f907d474ab9799bd1ad8dde8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":262,
              "y":485},
            "size":{
              "width":538,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"398b8dedeaee42778c23fe3dc5b8b812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":262,
                  "y":485},
                "size":{
                  "width":538,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d187929ba2064861a0aa644783f0db21",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":556},
            "size":{
              "width":550,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/满意度评价/u74_line.png"}},
{
          "id":"ec8bbc04165a43358ece74fea23b511e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":742,
              "y":421},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cccfa4a304e744ab92f6882ba6222e84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":742,
                  "y":421},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u75.png"}},
{
          "id":"1e02eaf2de79419f93cb480e3a4ffac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":742,
              "y":488},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6ce81aa409b4d7385f26cddc28fe4bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":742,
                  "y":488},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u93.png"}},
{
          "id":"530405f0746c4964ad865b685b8e75d6",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":517},
            "size":{
              "width":478,
              "height":38}},
          "adaptiveStyles":{
}},
{
          "id":"2964f7bcbeb94739b55fb18ba49ad724",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":742,
              "y":535},
            "size":{
              "width":58,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1d0930a1b9a42718af0163b7534aaf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":742,
                  "y":535},
                "size":{
                  "width":58,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/满意度评价/u96.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "03c1666168c94e3baf1d3bfe07423490":{
      "scriptId":"u0"},
    "ff627f7127eb4afb87ab2df30c85a1bd":{
      "scriptId":"u1"},
    "b46407a373914665b508a311f364fb8d":{
      "scriptId":"u2"},
    "d8abc925174c41dd8fd6f814e411cff5":{
      "scriptId":"u3"},
    "0252a9a268be4ef2818280d0717b9ce9":{
      "scriptId":"u4"},
    "e1a4cecc964043958d90ac80512dff73":{
      "scriptId":"u5"},
    "f511c452d4a14dffbe4c0847eddf625d":{
      "scriptId":"u6"},
    "e4e3c5790d0b42c0b001030fb1957b71":{
      "scriptId":"u7"},
    "89525d7147e54c5dbc646879351c7966":{
      "scriptId":"u8"},
    "2003e953eaab478b9d8d70ab743a5247":{
      "scriptId":"u9"},
    "aad78a3a8e8741a2939eafbd5b257208":{
      "scriptId":"u10"},
    "1154c207ed6a488f9598b2fdb9b72373":{
      "scriptId":"u11"},
    "3f7f4fb5082e4988811fc8b4a23851c4":{
      "scriptId":"u12"},
    "1c88e13368e84bbcbed34b0efc9ddd49":{
      "scriptId":"u13"},
    "1c7304ef9d684a2d90cc3f056fa5248c":{
      "scriptId":"u14"},
    "eae9760916f9424c9917598b067074c6":{
      "scriptId":"u15"},
    "ed860859a0a24b1e8f1161c8d549cc71":{
      "scriptId":"u16"},
    "b86996885e3445d58c07b06256ea0921":{
      "scriptId":"u17"},
    "8ca4e3badb92405b8f60f4698388bce7":{
      "scriptId":"u18"},
    "4bc5b73c08db441da45be3fdff6e5471":{
      "scriptId":"u19"},
    "4d2cb1543b524828987bf2d62d9e9caf":{
      "scriptId":"u20"},
    "e9c8fce9811948daa0f207789af7475e":{
      "scriptId":"u21"},
    "c998ed93cbb64e23a970f3ea6ea88915":{
      "scriptId":"u22"},
    "3f37dd473e0449538fb2674829e2b35f":{
      "scriptId":"u23"},
    "cacdd89a528344dfa8058ef91bd846d1":{
      "scriptId":"u24"},
    "7c3ec3da4c834fc4adba428959365fbb":{
      "scriptId":"u25"},
    "d5daf66c73ff4b5b88fb4161a1b6009d":{
      "scriptId":"u26"},
    "8ffb3eb8450d4d33b53b35c5f5425974":{
      "scriptId":"u27"},
    "96f2060315414ec8943fe2e6b11dbc0f":{
      "scriptId":"u28"},
    "d27c5e6343d0416f9a1ff24c5cd07755":{
      "scriptId":"u29"},
    "b57edcd60cdb45808ac39c133eef85de":{
      "scriptId":"u30"},
    "43c3bc78b6284cbd806cc9f40debb658":{
      "scriptId":"u31"},
    "89b019dab1b04cadb3b9a519186fc70b":{
      "scriptId":"u32"},
    "7ff2fccf858348e0892846d382b4a22b":{
      "scriptId":"u33"},
    "dd8eeff987774ec79e928768ccbd9cb7":{
      "scriptId":"u34"},
    "434de672b0bf44639eabacde8cfd3ab3":{
      "scriptId":"u35"},
    "b2df02b8672f4ac39112063cb8770d13":{
      "scriptId":"u36"},
    "d89ee1e4aaf748deba51d948bd82a93b":{
      "scriptId":"u37"},
    "8c186dca97f4419a8dc82135c8a06c87":{
      "scriptId":"u38"},
    "b9d08114d29f43ef9c8270c8391d9375":{
      "scriptId":"u39"},
    "988bbc16994f43a5a9801c799d12121d":{
      "scriptId":"u40"},
    "3db4d053277d4950adc7ecca54e454b0":{
      "scriptId":"u41"},
    "c0742472d40b43a78616f2972fe10445":{
      "scriptId":"u42"},
    "d58ee195d49a4fe1affb4c99fbe76cf0":{
      "scriptId":"u43"},
    "5f7241f5d1bc4a95955fc632febeb8e0":{
      "scriptId":"u44"},
    "0c9a004d348a460e88fc57a4b0d081ae":{
      "scriptId":"u45"},
    "58b87410cbe6483d8d031161fb3059e1":{
      "scriptId":"u46"},
    "b1650839b2614722b6dc5bbe3b3f8745":{
      "scriptId":"u47"},
    "aa3eb74103134c5baffb4073886d6ae4":{
      "scriptId":"u48"},
    "9efb951a56ca4035a5ef65b22050116c":{
      "scriptId":"u49"},
    "a6f1226af4ea44e48806b7d30249acaa":{
      "scriptId":"u50"},
    "d5ce440aeb924762b6bb943b6514a486":{
      "scriptId":"u51"},
    "26a57ef67c81421f98f42f4580afd175":{
      "scriptId":"u52"},
    "58873b1d017c4ee4b8c8b0743853fa92":{
      "scriptId":"u53"},
    "26eece99fd6d43aca84a3fa6260624e1":{
      "scriptId":"u54"},
    "2aa4020c55d64d4dac57f75ec1363af4":{
      "scriptId":"u55"},
    "2c31e47c70814f12a81f70df5a98355d":{
      "scriptId":"u56"},
    "8bcd03196da44191a81c489a83aa66e7":{
      "scriptId":"u57"},
    "6c4e0f18015d42588fc3d21f1018dcaa":{
      "scriptId":"u58"},
    "764b491f3ffe46fba8a92d8a077cd53c":{
      "scriptId":"u59"},
    "b06ae73baa04479cb9edde843695954c":{
      "scriptId":"u60"},
    "e1141047d8db47e28c185883d94bd5e7":{
      "scriptId":"u61"},
    "8536000be5b34a3cbe4faaafe50591ff":{
      "scriptId":"u62"},
    "71f40a1ffdd040a89a507d1d8bf2846c":{
      "scriptId":"u63"},
    "0d674d6d07ce4c68a8889dacb7f42f6f":{
      "scriptId":"u64"},
    "3edbf1b74ede4a21be36f7456128dc33":{
      "scriptId":"u65"},
    "3366776b1d724963a3d787500dfb6d06":{
      "scriptId":"u66"},
    "00d25031a95946ed843ca7a49b434e0d":{
      "scriptId":"u67"},
    "0c3cdaaa23e44549b47db71a98f20d65":{
      "scriptId":"u68"},
    "d4eaeab269994de0a6c587a754133fb0":{
      "scriptId":"u69"},
    "d144b30c80fc43a19b0a1a030f4a7f48":{
      "scriptId":"u70"},
    "e7f1910b5fdf466987ac5fbeb2a8c12c":{
      "scriptId":"u71"},
    "15204e0792634ddfa39a23885715b888":{
      "scriptId":"u72"},
    "392a8c8a19214aea919d00eeedd6644e":{
      "scriptId":"u73"},
    "b10f5ca9430748d2b3d725665a191c79":{
      "scriptId":"u74"},
    "a1907a1dd4464350aefa8b33ad2bbc08":{
      "scriptId":"u75"},
    "2077ba1bccd74b85977a9ce731a1c076":{
      "scriptId":"u76"},
    "b2d050f4dbdb4d6f9881d47e5fb52876":{
      "scriptId":"u77"},
    "c71c099c8a664dfabb407d9eca195ba2":{
      "scriptId":"u78"},
    "27689801a8ac437a8f034c60e9590177":{
      "scriptId":"u79"},
    "0b0b9f62640c4f8184a10745548d8482":{
      "scriptId":"u80"},
    "c0b861cd1a7a43a5b0fe88b512c6557d":{
      "scriptId":"u81"},
    "edc01c65b397435088b8cc45a753f68c":{
      "scriptId":"u82"},
    "67423c7558aa40df92daf9cc0c41a3ae":{
      "scriptId":"u83"},
    "69166b69627545eebe8c4006dc8c0691":{
      "scriptId":"u84"},
    "1711dba891d5479494c0447a921f2373":{
      "scriptId":"u85"},
    "65cdf2ff46854db685fe0596fb56ff31":{
      "scriptId":"u86"},
    "4a8fb95baa6f49548ccd9133f67dccd8":{
      "scriptId":"u87"},
    "ddad5c0f907d474ab9799bd1ad8dde8b":{
      "scriptId":"u88"},
    "398b8dedeaee42778c23fe3dc5b8b812":{
      "scriptId":"u89"},
    "d187929ba2064861a0aa644783f0db21":{
      "scriptId":"u90"},
    "ec8bbc04165a43358ece74fea23b511e":{
      "scriptId":"u91"},
    "cccfa4a304e744ab92f6882ba6222e84":{
      "scriptId":"u92"},
    "1e02eaf2de79419f93cb480e3a4ffac2":{
      "scriptId":"u93"},
    "f6ce81aa409b4d7385f26cddc28fe4bb":{
      "scriptId":"u94"},
    "530405f0746c4964ad865b685b8e75d6":{
      "scriptId":"u95"},
    "2964f7bcbeb94739b55fb18ba49ad724":{
      "scriptId":"u96"},
    "a1d0930a1b9a42718af0163b7534aaf8":{
      "scriptId":"u97"}}});