$axure.loadCurrentPage({
  "url":"店铺信息.html",
  "generationDate":new Date(1413021310904.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"00d7b7dbd3254c239c9bd2a21a7af56b",
    "type":"Axure:Page",
    "name":"店铺信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c1666168c94e3baf1d3bfe07423490",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":970,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff627f7127eb4afb87ab2df30c85a1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":970,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u0.png"}},
{
          "id":"b46407a373914665b508a311f364fb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":0,
              "y":67},
            "size":{
              "width":100,
              "height":914},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8abc925174c41dd8fd6f814e411cff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":0,
                  "y":67},
                "size":{
                  "width":100,
                  "height":914},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u2.png"}},
{
          "id":"0252a9a268be4ef2818280d0717b9ce9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":100,
              "y":67},
            "size":{
              "width":768,
              "height":914},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a4cecc964043958d90ac80512dff73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":100,
                  "y":67},
                "size":{
                  "width":768,
                  "height":914},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u4.png"}},
{
          "id":"f511c452d4a14dffbe4c0847eddf625d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":868,
              "y":67},
            "size":{
              "width":100,
              "height":914},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e3c5790d0b42c0b001030fb1957b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":868,
                  "y":67},
                "size":{
                  "width":100,
                  "height":914},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u2.png"}},
{
          "id":"89525d7147e54c5dbc646879351c7966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":981},
            "size":{
              "width":970,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2003e953eaab478b9d8d70ab743a5247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":981},
                "size":{
                  "width":970,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u36.png"}},
{
          "id":"aad78a3a8e8741a2939eafbd5b257208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":990},
            "size":{
              "width":970,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1154c207ed6a488f9598b2fdb9b72373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":990},
                "size":{
                  "width":970,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u38.png"}},
{
          "id":"3f7f4fb5082e4988811fc8b4a23851c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":1002},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c88e13368e84bbcbed34b0efc9ddd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":1002},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c7304ef9d684a2d90cc3f056fa5248c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":1002},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae9760916f9424c9917598b067074c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":1002},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed860859a0a24b1e8f1161c8d549cc71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":444,
              "y":1002},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86996885e3445d58c07b06256ea0921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":444,
                  "y":1002},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca4e3badb92405b8f60f4698388bce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":600,
              "y":1002},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc5b73c08db441da45be3fdff6e5471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":600,
                  "y":1002},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2cb1543b524828987bf2d62d9e9caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":180,
              "y":1043},
            "size":{
              "width":730,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c8fce9811948daa0f207789af7475e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":1043},
                "size":{
                  "width":730,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c998ed93cbb64e23a970f3ea6ea88915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":105},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f37dd473e0449538fb2674829e2b35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":105},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cacdd89a528344dfa8058ef91bd846d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":130},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3ec3da4c834fc4adba428959365fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":130},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5daf66c73ff4b5b88fb4161a1b6009d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":156},
            "size":{
              "width":80,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffb3eb8450d4d33b53b35c5f5425974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":156},
                "size":{
                  "width":80,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f2060315414ec8943fe2e6b11dbc0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":181},
            "size":{
              "width":90,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d27c5e6343d0416f9a1ff24c5cd07755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":181},
                "size":{
                  "width":90,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26eece99fd6d43aca84a3fa6260624e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":262,
              "y":89},
            "size":{
              "width":145,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa4020c55d64d4dac57f75ec1363af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":262,
                  "y":89},
                "size":{
                  "width":145,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40497f502fae4039b2b2b1913dcc4607",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":138,
              "y":202},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a418f863ee544ab8bd53abefc67d9248",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":202},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a74a29e8f0954f0ca8eff67ecd452970",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":405,
              "y":130},
            "size":{
              "width":275,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"309351a9f78a48d4951b0c306dcd4a24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":292,
              "y":134},
            "size":{
              "width":140,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"148b5abf12b549698130af36e350d7e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":292,
                  "y":134},
                "size":{
                  "width":140,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edde022383c44cd9bf5aec6df222e238",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC00},
            "location":{
              "x":489.5,
              "y":931},
            "size":{
              "width":130,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db70359da5d04822919946e17a166b19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00},
                "location":{
                  "x":489.5,
                  "y":931},
                "size":{
                  "width":130,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u37.png"}},
{
          "id":"83570b6b816243fc86eca6cdbdb48b47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":269,
              "y":500},
            "size":{
              "width":140,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e20d115629e84e63a83aecc574f0b039",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":269,
                  "y":500},
                "size":{
                  "width":140,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee33d58de30144dfbb0b87746862e78e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":269,
              "y":492},
            "size":{
              "width":564,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/店铺信息/u41_line.png"}},
{
          "id":"03f105a4e556438e9c4c1c823fc2f923",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":405,
              "y":157},
            "size":{
              "width":275,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6ca86651283343d587c6691a289a43d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":292,
              "y":161},
            "size":{
              "width":140,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d48128943ed4908b653519f175746b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":292,
                  "y":161},
                "size":{
                  "width":140,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0da81159b524e928d3a0fbafa02fc2c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":405,
              "y":184},
            "size":{
              "width":275,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e63b3c34e7a1499b9e89ecb59bd25429",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":292,
              "y":188},
            "size":{
              "width":140,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d41121e8febf438c80a2c285f7a9801e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":292,
                  "y":188},
                "size":{
                  "width":140,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a5e5bb6dd064578916924ccbf47eb70",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":405,
              "y":210},
            "size":{
              "width":275,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"78a8c68ec5194b138931a0997fc5eda9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":292,
              "y":214},
            "size":{
              "width":140,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2df661174a645a3a768d577b36d84f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":292,
                  "y":214},
                "size":{
                  "width":140,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4ad130e380f4c96aaf145cd6c97ee70",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":405,
              "y":237},
            "size":{
              "width":275,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4465e330629f4923922e84e533e78a15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":292,
              "y":241},
            "size":{
              "width":140,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7ab72094b4743e88e55841a7149bd31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":292,
                  "y":241},
                "size":{
                  "width":140,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb4b9ea6af2e47dcb4c094a1453d8a7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":292,
              "y":303},
            "size":{
              "width":140,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37f812d92a0b4a56a885f8bb53f6e7e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":292,
                  "y":303},
                "size":{
                  "width":140,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce0d361c9e4b4308a0a1bbd5be086a58",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":303},
            "size":{
              "width":245,
              "height":147}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70e7dae33490493b99f4a8d441636aa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":303},
                "size":{
                  "width":245,
                  "height":147}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u56.png"}},
{
          "id":"1946de17bcd940f4b5747330f077783c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":405,
              "y":262},
            "size":{
              "width":275,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bc5c90a40c044dc8a7b35426532b8c53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":292,
              "y":266},
            "size":{
              "width":140,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ad12666efb44286b196de95edde0933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":292,
                  "y":266},
                "size":{
                  "width":140,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9dc5355ecf5f4d879b97e292f3f13c8e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":526},
            "size":{
              "width":551,
              "height":228}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"498252ed3d1c40d7bf1f4507fd3f2f34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":526},
                "size":{
                  "width":551,
                  "height":228}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u61.jpg"}},
{
          "id":"7c65ac97a4544194934956a72cd3f8ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":764},
            "size":{
              "width":552,
              "height":159}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57ee416f44564d5bbbef651e7c56515a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":764},
                "size":{
                  "width":552,
                  "height":159}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u63.png"}},
{
          "id":"ca2dc1c506cc4fe993ac24e4ba32f95e",
          "label":"fendian",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":292,
              "y":245},
            "size":{
              "width":538,
              "height":475},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"274a5f66448a4decbafcb86c1ebbe80f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"317793f4fe674fffb4b4958d0830b1c1",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":540,
                      "height":480}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1fb4b02f3ed4d74b10909eb949ce17e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":540,
                          "height":480}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺信息/u66.png"}},
{
                  "id":"af7eba421f604a45a4b32f80d8546c33",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"bold",
                    "location":{
                      "x":42,
                      "y":9},
                    "size":{
                      "width":145,
                      "height":21},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e9f3893f207410ea9e460dfaa87ed5a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"bold",
                        "location":{
                          "x":42,
                          "y":9},
                        "size":{
                          "width":145,
                          "height":21},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0374808e2a5f48a1b794536f4c48c4dc",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":50},
                    "size":{
                      "width":275,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"0417f7a134654cc99683887a80f9f1f8",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":54},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfa69e6f2a4b49388388c786224c14c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":54},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"99d0db36f2a949a3964c614620b3defc",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":77},
                    "size":{
                      "width":275,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"2dec625b49c048f8870af8a8b5fd2bd6",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":81},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79cffed81df94e31b1bd91aa8a346b6f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":81},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eb4618721c4b40b68d8a79cc2c16f971",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":103},
                    "size":{
                      "width":275,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"28a7920465654193bcbcae3272bec80e",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":107},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a03476a58d24dec993cca95817912fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":107},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e1874c788aa04019afe23826ffd50d8b",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":130},
                    "size":{
                      "width":275,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"49e7a0e4ab3943cda56edbd98f0cfa5f",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":134},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d8828b4d5a55420f9a7f24046fe61e8a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":134},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2c345c597a154373827c2fd5d7734973",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":158},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1a33c2f2ecc49cbb550768f5b366fdb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":158},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a611d52070654bc88318b368995db058",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":185,
                      "y":158},
                    "size":{
                      "width":275,
                      "height":162}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52e3892995ba4dac89ab759d736b1b27",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":185,
                          "y":158},
                        "size":{
                          "width":275,
                          "height":162}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺信息/u56.png"}},
{
                  "id":"690faf44fff5402fbefc8b2b2650a135",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC00},
                    "location":{
                      "x":170,
                      "y":420},
                    "size":{
                      "width":130,
                      "height":40},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df4b36ab1b4947ef9fc18253bc77d3da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFCC00},
                        "location":{
                          "x":170,
                          "y":420},
                        "size":{
                          "width":130,
                          "height":40},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺信息/u37.png"}},
{
                  "id":"5e23ff8423864eef95235d02231304e2",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":330},
                    "size":{
                      "width":275,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"0296c6e4b84240dc922476694c8bc23e",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":334},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a2b0aab9fdbd4464a4117c6b8de7dbea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":334},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9aa27076bd934804920f059d575ffe3c",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":357},
                    "size":{
                      "width":275,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"6aad650a5ef749c08c7eea7b89e8d2db",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":361},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b0cc1362ee0477a9b299b0235d670f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":361},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"15559f34845641feb9698f83794dae31",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":383},
                    "size":{
                      "width":275,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"87cc7114cd624475ac2789ad8daa16c4",
                  "label":"",
                  "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":387},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35e96c61eee14f6a875e91bb13036066",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca2dc1c506cc4fe993ac24e4ba32f95e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":387},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"3287a4762f02425abeb40a41b24f1493",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":387,
              "y":470},
            "size":{
              "width":80,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e8dcb1f5aec4597825320619266d280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":387,
                  "y":470},
                "size":{
                  "width":80,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 fendian 置于顶层",
                      "objectsToFades":[{
                          "objectPath":["ca2dc1c506cc4fe993ac24e4ba32f95e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"front"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/店铺信息/u97.png"}},
{
          "id":"cb8684bca94740ac8ef005f0de721797",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":293,
              "y":470},
            "size":{
              "width":100,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3ec1c24198e4133ba2aa29f7a29a5be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":293,
                  "y":470},
                "size":{
                  "width":100,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "03c1666168c94e3baf1d3bfe07423490":{
      "scriptId":"u0"},
    "ff627f7127eb4afb87ab2df30c85a1bd":{
      "scriptId":"u1"},
    "b46407a373914665b508a311f364fb8d":{
      "scriptId":"u2"},
    "d8abc925174c41dd8fd6f814e411cff5":{
      "scriptId":"u3"},
    "0252a9a268be4ef2818280d0717b9ce9":{
      "scriptId":"u4"},
    "e1a4cecc964043958d90ac80512dff73":{
      "scriptId":"u5"},
    "f511c452d4a14dffbe4c0847eddf625d":{
      "scriptId":"u6"},
    "e4e3c5790d0b42c0b001030fb1957b71":{
      "scriptId":"u7"},
    "89525d7147e54c5dbc646879351c7966":{
      "scriptId":"u8"},
    "2003e953eaab478b9d8d70ab743a5247":{
      "scriptId":"u9"},
    "aad78a3a8e8741a2939eafbd5b257208":{
      "scriptId":"u10"},
    "1154c207ed6a488f9598b2fdb9b72373":{
      "scriptId":"u11"},
    "3f7f4fb5082e4988811fc8b4a23851c4":{
      "scriptId":"u12"},
    "1c88e13368e84bbcbed34b0efc9ddd49":{
      "scriptId":"u13"},
    "1c7304ef9d684a2d90cc3f056fa5248c":{
      "scriptId":"u14"},
    "eae9760916f9424c9917598b067074c6":{
      "scriptId":"u15"},
    "ed860859a0a24b1e8f1161c8d549cc71":{
      "scriptId":"u16"},
    "b86996885e3445d58c07b06256ea0921":{
      "scriptId":"u17"},
    "8ca4e3badb92405b8f60f4698388bce7":{
      "scriptId":"u18"},
    "4bc5b73c08db441da45be3fdff6e5471":{
      "scriptId":"u19"},
    "4d2cb1543b524828987bf2d62d9e9caf":{
      "scriptId":"u20"},
    "e9c8fce9811948daa0f207789af7475e":{
      "scriptId":"u21"},
    "c998ed93cbb64e23a970f3ea6ea88915":{
      "scriptId":"u22"},
    "3f37dd473e0449538fb2674829e2b35f":{
      "scriptId":"u23"},
    "cacdd89a528344dfa8058ef91bd846d1":{
      "scriptId":"u24"},
    "7c3ec3da4c834fc4adba428959365fbb":{
      "scriptId":"u25"},
    "d5daf66c73ff4b5b88fb4161a1b6009d":{
      "scriptId":"u26"},
    "8ffb3eb8450d4d33b53b35c5f5425974":{
      "scriptId":"u27"},
    "96f2060315414ec8943fe2e6b11dbc0f":{
      "scriptId":"u28"},
    "d27c5e6343d0416f9a1ff24c5cd07755":{
      "scriptId":"u29"},
    "26eece99fd6d43aca84a3fa6260624e1":{
      "scriptId":"u30"},
    "2aa4020c55d64d4dac57f75ec1363af4":{
      "scriptId":"u31"},
    "40497f502fae4039b2b2b1913dcc4607":{
      "scriptId":"u32"},
    "a418f863ee544ab8bd53abefc67d9248":{
      "scriptId":"u33"},
    "a74a29e8f0954f0ca8eff67ecd452970":{
      "scriptId":"u34"},
    "309351a9f78a48d4951b0c306dcd4a24":{
      "scriptId":"u35"},
    "148b5abf12b549698130af36e350d7e0":{
      "scriptId":"u36"},
    "edde022383c44cd9bf5aec6df222e238":{
      "scriptId":"u37"},
    "db70359da5d04822919946e17a166b19":{
      "scriptId":"u38"},
    "83570b6b816243fc86eca6cdbdb48b47":{
      "scriptId":"u39"},
    "e20d115629e84e63a83aecc574f0b039":{
      "scriptId":"u40"},
    "ee33d58de30144dfbb0b87746862e78e":{
      "scriptId":"u41"},
    "03f105a4e556438e9c4c1c823fc2f923":{
      "scriptId":"u42"},
    "6ca86651283343d587c6691a289a43d5":{
      "scriptId":"u43"},
    "4d48128943ed4908b653519f175746b9":{
      "scriptId":"u44"},
    "c0da81159b524e928d3a0fbafa02fc2c":{
      "scriptId":"u45"},
    "e63b3c34e7a1499b9e89ecb59bd25429":{
      "scriptId":"u46"},
    "d41121e8febf438c80a2c285f7a9801e":{
      "scriptId":"u47"},
    "1a5e5bb6dd064578916924ccbf47eb70":{
      "scriptId":"u48"},
    "78a8c68ec5194b138931a0997fc5eda9":{
      "scriptId":"u49"},
    "b2df661174a645a3a768d577b36d84f0":{
      "scriptId":"u50"},
    "a4ad130e380f4c96aaf145cd6c97ee70":{
      "scriptId":"u51"},
    "4465e330629f4923922e84e533e78a15":{
      "scriptId":"u52"},
    "b7ab72094b4743e88e55841a7149bd31":{
      "scriptId":"u53"},
    "cb4b9ea6af2e47dcb4c094a1453d8a7d":{
      "scriptId":"u54"},
    "37f812d92a0b4a56a885f8bb53f6e7e8":{
      "scriptId":"u55"},
    "ce0d361c9e4b4308a0a1bbd5be086a58":{
      "scriptId":"u56"},
    "70e7dae33490493b99f4a8d441636aa5":{
      "scriptId":"u57"},
    "1946de17bcd940f4b5747330f077783c":{
      "scriptId":"u58"},
    "bc5c90a40c044dc8a7b35426532b8c53":{
      "scriptId":"u59"},
    "5ad12666efb44286b196de95edde0933":{
      "scriptId":"u60"},
    "9dc5355ecf5f4d879b97e292f3f13c8e":{
      "scriptId":"u61"},
    "498252ed3d1c40d7bf1f4507fd3f2f34":{
      "scriptId":"u62"},
    "7c65ac97a4544194934956a72cd3f8ef":{
      "scriptId":"u63"},
    "57ee416f44564d5bbbef651e7c56515a":{
      "scriptId":"u64"},
    "ca2dc1c506cc4fe993ac24e4ba32f95e":{
      "scriptId":"u65"},
    "317793f4fe674fffb4b4958d0830b1c1":{
      "scriptId":"u66"},
    "e1fb4b02f3ed4d74b10909eb949ce17e":{
      "scriptId":"u67"},
    "af7eba421f604a45a4b32f80d8546c33":{
      "scriptId":"u68"},
    "7e9f3893f207410ea9e460dfaa87ed5a":{
      "scriptId":"u69"},
    "0374808e2a5f48a1b794536f4c48c4dc":{
      "scriptId":"u70"},
    "0417f7a134654cc99683887a80f9f1f8":{
      "scriptId":"u71"},
    "bfa69e6f2a4b49388388c786224c14c1":{
      "scriptId":"u72"},
    "99d0db36f2a949a3964c614620b3defc":{
      "scriptId":"u73"},
    "2dec625b49c048f8870af8a8b5fd2bd6":{
      "scriptId":"u74"},
    "79cffed81df94e31b1bd91aa8a346b6f":{
      "scriptId":"u75"},
    "eb4618721c4b40b68d8a79cc2c16f971":{
      "scriptId":"u76"},
    "28a7920465654193bcbcae3272bec80e":{
      "scriptId":"u77"},
    "9a03476a58d24dec993cca95817912fd":{
      "scriptId":"u78"},
    "e1874c788aa04019afe23826ffd50d8b":{
      "scriptId":"u79"},
    "49e7a0e4ab3943cda56edbd98f0cfa5f":{
      "scriptId":"u80"},
    "d8828b4d5a55420f9a7f24046fe61e8a":{
      "scriptId":"u81"},
    "2c345c597a154373827c2fd5d7734973":{
      "scriptId":"u82"},
    "c1a33c2f2ecc49cbb550768f5b366fdb":{
      "scriptId":"u83"},
    "a611d52070654bc88318b368995db058":{
      "scriptId":"u84"},
    "52e3892995ba4dac89ab759d736b1b27":{
      "scriptId":"u85"},
    "690faf44fff5402fbefc8b2b2650a135":{
      "scriptId":"u86"},
    "df4b36ab1b4947ef9fc18253bc77d3da":{
      "scriptId":"u87"},
    "5e23ff8423864eef95235d02231304e2":{
      "scriptId":"u88"},
    "0296c6e4b84240dc922476694c8bc23e":{
      "scriptId":"u89"},
    "a2b0aab9fdbd4464a4117c6b8de7dbea":{
      "scriptId":"u90"},
    "9aa27076bd934804920f059d575ffe3c":{
      "scriptId":"u91"},
    "6aad650a5ef749c08c7eea7b89e8d2db":{
      "scriptId":"u92"},
    "1b0cc1362ee0477a9b299b0235d670f6":{
      "scriptId":"u93"},
    "15559f34845641feb9698f83794dae31":{
      "scriptId":"u94"},
    "87cc7114cd624475ac2789ad8daa16c4":{
      "scriptId":"u95"},
    "35e96c61eee14f6a875e91bb13036066":{
      "scriptId":"u96"},
    "3287a4762f02425abeb40a41b24f1493":{
      "scriptId":"u97"},
    "4e8dcb1f5aec4597825320619266d280":{
      "scriptId":"u98"},
    "cb8684bca94740ac8ef005f0de721797":{
      "scriptId":"u99"},
    "a3ec1c24198e4133ba2aa29f7a29a5be":{
      "scriptId":"u100"}}});