$axure.loadCurrentPage({
  "url":"再次上线.html",
  "generationDate":new Date(1412907464249.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"343ed5a002f44375a39c3b514c26bf6c",
    "type":"Axure:Page",
    "name":"再次上线",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c1666168c94e3baf1d3bfe07423490",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":970,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff627f7127eb4afb87ab2df30c85a1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":970,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u10.png"}},
{
          "id":"b46407a373914665b508a311f364fb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":0,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8abc925174c41dd8fd6f814e411cff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":0,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"0252a9a268be4ef2818280d0717b9ce9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":100,
              "y":67},
            "size":{
              "width":768,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a4cecc964043958d90ac80512dff73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":100,
                  "y":67},
                "size":{
                  "width":768,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购券状态查询/u4.png"}},
{
          "id":"f511c452d4a14dffbe4c0847eddf625d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":868,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e3c5790d0b42c0b001030fb1957b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":868,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"89525d7147e54c5dbc646879351c7966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":608},
            "size":{
              "width":970,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2003e953eaab478b9d8d70ab743a5247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":608},
                "size":{
                  "width":970,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u36.png"}},
{
          "id":"aad78a3a8e8741a2939eafbd5b257208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":970,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1154c207ed6a488f9598b2fdb9b72373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":617},
                "size":{
                  "width":970,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u38.png"}},
{
          "id":"3f7f4fb5082e4988811fc8b4a23851c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c88e13368e84bbcbed34b0efc9ddd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c7304ef9d684a2d90cc3f056fa5248c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae9760916f9424c9917598b067074c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed860859a0a24b1e8f1161c8d549cc71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":444,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86996885e3445d58c07b06256ea0921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":444,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca4e3badb92405b8f60f4698388bce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":600,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc5b73c08db441da45be3fdff6e5471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":600,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2cb1543b524828987bf2d62d9e9caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":180,
              "y":670},
            "size":{
              "width":730,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c8fce9811948daa0f207789af7475e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":670},
                "size":{
                  "width":730,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c998ed93cbb64e23a970f3ea6ea88915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":105},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f37dd473e0449538fb2674829e2b35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":105},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cacdd89a528344dfa8058ef91bd846d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":130},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3ec3da4c834fc4adba428959365fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":130},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5daf66c73ff4b5b88fb4161a1b6009d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":156},
            "size":{
              "width":80,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffb3eb8450d4d33b53b35c5f5425974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":156},
                "size":{
                  "width":80,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f2060315414ec8943fe2e6b11dbc0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":181},
            "size":{
              "width":90,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d27c5e6343d0416f9a1ff24c5cd07755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":181},
                "size":{
                  "width":90,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b57edcd60cdb45808ac39c133eef85de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":205},
            "size":{
              "width":92,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c3bc78b6284cbd806cc9f40debb658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":205},
                "size":{
                  "width":92,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89b019dab1b04cadb3b9a519186fc70b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":231},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff2fccf858348e0892846d382b4a22b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":231},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd8eeff987774ec79e928768ccbd9cb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":255},
            "size":{
              "width":91,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"434de672b0bf44639eabacde8cfd3ab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":255},
                "size":{
                  "width":91,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2df02b8672f4ac39112063cb8770d13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":141,
              "y":279},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d89ee1e4aaf748deba51d948bd82a93b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":279},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c186dca97f4419a8dc82135c8a06c87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":347},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d08114d29f43ef9c8270c8391d9375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":347},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"988bbc16994f43a5a9801c799d12121d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":373},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3db4d053277d4950adc7ecca54e454b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":373},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0742472d40b43a78616f2972fe10445",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":398},
            "size":{
              "width":100,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58ee195d49a4fe1affb4c99fbe76cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":398},
                "size":{
                  "width":100,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f7241f5d1bc4a95955fc632febeb8e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":265,
              "y":87},
            "size":{
              "width":234,
              "height":35},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c9a004d348a460e88fc57a4b0d081ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":265,
                  "y":87},
                "size":{
                  "width":234,
                  "height":35},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58b87410cbe6483d8d031161fb3059e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":492,
              "y":71},
            "size":{
              "width":323,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1650839b2614722b6dc5bbe3b3f8745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":492,
                  "y":71},
                "size":{
                  "width":323,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/团购券状态查询/u44.png"}},
{
          "id":"aa3eb74103134c5baffb4073886d6ae4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":509,
              "y":87},
            "size":{
              "width":259,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9efb951a56ca4035a5ef65b22050116c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":509,
                  "y":87},
                "size":{
                  "width":259,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6f1226af4ea44e48806b7d30249acaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":302},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ce440aeb924762b6bb943b6514a486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":302},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26a57ef67c81421f98f42f4580afd175",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":324},
            "size":{
              "width":89,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58873b1d017c4ee4b8c8b0743853fa92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":324},
                "size":{
                  "width":89,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c7d5c9c54954276a2c059dc7cfb8b14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":260,
              "y":140},
            "size":{
              "width":580,
              "height":65},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c003438e8e5a4f47af77f3358585338c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":260,
                  "y":140},
                "size":{
                  "width":580,
                  "height":65},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目合作数据/u48.png"}},
{
          "id":"3e54722d019f4f0a9a9c353c2b607aff",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":275,
              "y":150},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ba61acb5ab240cdba45e19d59f2c7ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":275,
                  "y":150},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50125d6f1cba40b3a51ba06151dee662",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":181},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1a1882f2a0b4600b0faa0c62f3ee78a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":181},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaf4f463a27143f4b1ec6540bb52d93c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":400,
              "y":150},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8481001dce654831997b2ebf2a69c3b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":400,
                  "y":150},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"580eb6f0e05748fea435abb395e777e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":404,
              "y":181},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"980ff75177bf45e094f3a844c99e7a16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":404,
                  "y":181},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f59dc992f414b3dbbb3adbd31cfa690",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":530,
              "y":150},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e172fcc2ae84eadb91b1f363591e9f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":530,
                  "y":150},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d60bfdb5ff648bfb3f5a2b2ec8e7258",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":181},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"695c6ef773354715bd3e2ba4322b53e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":181},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bb22ba8362540b691c1f6e77b639e76",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":657,
              "y":150},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3ad6bd33ab348b18c6467eb4431eadf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":657,
                  "y":150},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05989f22dd8b46dc96407e8cd4d20936",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":181},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b58d7ae83f64e4eb63423f8c50f19a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":181},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dea28092f60342a0a8d1317774f6f7ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":760,
              "y":150},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff1be16ff2a246b0bd9306b5a525003a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":760,
                  "y":150},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de7a23b6af4d4697989d7b76b15426c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":769,
              "y":181},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"993eecb3a4734211a6039f32603576d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":769,
                  "y":181},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0323876e740247c18908d3d232a8db93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":444,
              "y":398},
            "size":{
              "width":157,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecfb6f013a184d41a225fb070507604f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":444,
                  "y":398},
                "size":{
                  "width":157,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请延期/u82.png"}},
{
          "id":"867729a8470243348094454b10fdb617",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":457,
              "y":412},
            "size":{
              "width":130,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b39f1eb97e234ed0827a7c5e54730798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":457,
                  "y":412},
                "size":{
                  "width":130,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a7a11222c8c441394f2d1e9eebd2f4c",
          "label":"Date Input Field",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":235},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 Date Input Field = &quot;[[Year]]-[[Month]]-01&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["0a7a11222c8c441394f2d1e9eebd2f4c"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Year]]-[[Month]]-01",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"var",
                                    "name":"year"},
{
                                    "sto":"var",
                                    "name":"month"}]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"Case 1<br> (If 文字于 Date Input Field 等于 &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["0a7a11222c8c441394f2d1e9eebd2f4c"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 Date Input Field = &quot;[[Year]]-[[Month]]-01&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["0a7a11222c8c441394f2d1e9eebd2f4c"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Year]]-[[Month]]-01",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"var",
                                    "name":"year"},
{
                                    "sto":"var",
                                    "name":"month"}]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"dc534fcf6b7042fd9ec0668679ddb094",
          "label":"Calendar Icon Button",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":239},
            "size":{
              "width":16,
              "height":15},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF24307B}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84f0fa1044fd4dc3bcd72074f8a32127",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":239},
                "size":{
                  "width":16,
                  "height":15},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF24307B}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 Date Calendar 淡入淡出 50 ms",
                      "objectsToFades":[{
                          "objectPath":["b911744883744c82b7df8db8022c58c4"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "easing":"fade",
                              "duration":50,
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"移动 Date Calendar 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["b911744883744c82b7df8db8022c58c4"],
                          "setOrderInfo":{
                            "bringToFront":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/申请延期/calendar_icon_button_u71.png"}},
{
          "id":"b911744883744c82b7df8db8022c58c4",
          "label":"Date Calendar",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":526,
              "y":256},
            "size":{
              "width":200,
              "height":173},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onShow":{
              "description":"OnShow",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 Current Date1 = &quot;[[MonthName]] [[Year]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6589043b5b3d4d079821d392cf2bd6d4"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[MonthName]] [[Year]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"var",
                                    "name":"monthname"},
{
                                    "sto":"var",
                                    "name":"year"}]}]}]}}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"8ae0a21cca1a46a89207f4561fcff3f7",
              "label":"Default",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"be4f598434a44025872a977319dde32a",
                  "label":"",
                  "parentDynamicPanel":"b911744883744c82b7df8db8022c58c4",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":193,
                      "height":162},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"07a22a6e80ab4505b413d57d16b42749",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b911744883744c82b7df8db8022c58c4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":193,
                          "height":162},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/申请延期/u74.png"}},
{
                  "id":"f750e51569574b2eade174e900ed2975",
                  "label":"",
                  "parentDynamicPanel":"b911744883744c82b7df8db8022c58c4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFFFFFFF},
{
                          "color":0xFFFFFFFF},
{
                          "color":0xFFD4E6F1},
{
                          "color":0xFFD4E6F1}]},
                    "location":{
                      "x":45,
                      "y":4},
                    "size":{
                      "width":109,
                      "height":24},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6efd079654834f41a6c84867d52e8d03",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b911744883744c82b7df8db8022c58c4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFD4E6F1},
{
                              "color":0xFFD4E6F1}]},
                        "location":{
                          "x":45,
                          "y":4},
                        "size":{
                          "width":109,
                          "height":24},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/申请延期/u76.png"}},
{
                  "id":"7f6fd905d89d4bdd9b168a2372329160",
                  "label":"Date Selection",
                  "parentDynamicPanel":"b911744883744c82b7df8db8022c58c4",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":118},
                    "size":{
                      "width":30,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 Date Input Field = &quot;[[Year]]-[[Month]]-22&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["0a7a11222c8c441394f2d1e9eebd2f4c"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[Year]]-[[Month]]-22",
                                        "localVariables":{
},
                                        "stos":[{
                                            "sto":"var",
                                            "name":"year"},
{
                                            "sto":"var",
                                            "name":"month"}]}]}]}},
{
                              "action":"fadeWidget",
                              "description":"隐藏 Date Calendar 淡入淡出 50 ms",
                              "objectsToFades":[{
                                  "objectPath":["b911744883744c82b7df8db8022c58c4"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":50,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"6589043b5b3d4d079821d392cf2bd6d4",
                  "label":"Current Date1",
                  "parentDynamicPanel":"b911744883744c82b7df8db8022c58c4",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "horizontalAlignment":"center",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE5F0F6},
                    "location":{
                      "x":47,
                      "y":6},
                    "size":{
                      "width":103,
                      "height":20}},
                  "adaptiveStyles":{
}}]}]},
{
          "id":"ab4342f4b43a46bfad28d03796aa2843",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":287,
              "y":235},
            "size":{
              "width":169,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"649c0478afe5418386e599518b1c9686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":287,
                  "y":235},
                "size":{
                  "width":169,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a306afd8b1b3404ebcb3c6d492e7b3a0",
          "label":"Date Input Field",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":284},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 Date Input Field = &quot;[[Year]]-[[Month]]-01&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a306afd8b1b3404ebcb3c6d492e7b3a0"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Year]]-[[Month]]-01",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"var",
                                    "name":"year"},
{
                                    "sto":"var",
                                    "name":"month"}]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"Case 1<br> (If 文字于 Date Input Field 等于 &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["a306afd8b1b3404ebcb3c6d492e7b3a0"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 Date Input Field = &quot;[[Year]]-[[Month]]-01&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a306afd8b1b3404ebcb3c6d492e7b3a0"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Year]]-[[Month]]-01",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"var",
                                    "name":"year"},
{
                                    "sto":"var",
                                    "name":"month"}]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"5d68bdf2e45b45919eca9ad78fafa6f7",
          "label":"Calendar Icon Button",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":288},
            "size":{
              "width":16,
              "height":15},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF24307B}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69ce1b7884cf4cb7bc32c3c77cf70799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":288},
                "size":{
                  "width":16,
                  "height":15},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF24307B}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 Date Calendar 淡入淡出 50 ms",
                      "objectsToFades":[{
                          "objectPath":["945e1da61b1f4380978cabac7fb1c178"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "easing":"fade",
                              "duration":50,
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"移动 Date Calendar 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["945e1da61b1f4380978cabac7fb1c178"],
                          "setOrderInfo":{
                            "bringToFront":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/申请延期/calendar_icon_button_u71.png"}},
{
          "id":"945e1da61b1f4380978cabac7fb1c178",
          "label":"Date Calendar",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":526,
              "y":305},
            "size":{
              "width":200,
              "height":173},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onShow":{
              "description":"OnShow",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 Current Date1 = &quot;[[MonthName]] [[Year]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["49de96fd0b9a497492248e23444187de"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[MonthName]] [[Year]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"var",
                                    "name":"monthname"},
{
                                    "sto":"var",
                                    "name":"year"}]}]}]}}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b951fb49090e43298900f5892a36c1fb",
              "label":"Default",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b92dc68a25574cde956b9af5b6cc261c",
                  "label":"",
                  "parentDynamicPanel":"945e1da61b1f4380978cabac7fb1c178",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":193,
                      "height":162},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fed01872b3ea45e790da2dd9fec692d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"945e1da61b1f4380978cabac7fb1c178",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":193,
                          "height":162},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/申请延期/u74.png"}},
{
                  "id":"4e34bbeb294a4bb99909784c5da7ba1d",
                  "label":"",
                  "parentDynamicPanel":"945e1da61b1f4380978cabac7fb1c178",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFFFFFFF},
{
                          "color":0xFFFFFFFF},
{
                          "color":0xFFD4E6F1},
{
                          "color":0xFFD4E6F1}]},
                    "location":{
                      "x":45,
                      "y":4},
                    "size":{
                      "width":109,
                      "height":24},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ebb4f5e62fb7474eba510f9603d7189d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"945e1da61b1f4380978cabac7fb1c178",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFD4E6F1},
{
                              "color":0xFFD4E6F1}]},
                        "location":{
                          "x":45,
                          "y":4},
                        "size":{
                          "width":109,
                          "height":24},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/申请延期/u76.png"}},
{
                  "id":"6c21888b226942bc8bb9053d79b3ec4c",
                  "label":"Date Selection",
                  "parentDynamicPanel":"945e1da61b1f4380978cabac7fb1c178",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":118},
                    "size":{
                      "width":30,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 Date Input Field = &quot;[[Year]]-[[Month]]-22&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["a306afd8b1b3404ebcb3c6d492e7b3a0"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[Year]]-[[Month]]-22",
                                        "localVariables":{
},
                                        "stos":[{
                                            "sto":"var",
                                            "name":"year"},
{
                                            "sto":"var",
                                            "name":"month"}]}]}]}},
{
                              "action":"fadeWidget",
                              "description":"隐藏 Date Calendar 淡入淡出 50 ms",
                              "objectsToFades":[{
                                  "objectPath":["945e1da61b1f4380978cabac7fb1c178"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":50,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"49de96fd0b9a497492248e23444187de",
                  "label":"Current Date1",
                  "parentDynamicPanel":"945e1da61b1f4380978cabac7fb1c178",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "horizontalAlignment":"center",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE5F0F6},
                    "location":{
                      "x":47,
                      "y":6},
                    "size":{
                      "width":103,
                      "height":20}},
                  "adaptiveStyles":{
}}]}]},
{
          "id":"1bc92a89f08546c69a8c9de1876dfe95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":287,
              "y":284},
            "size":{
              "width":169,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abf4c63c5b684f719cd9b3a7e1ee4690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":287,
                  "y":284},
                "size":{
                  "width":169,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "03c1666168c94e3baf1d3bfe07423490":{
      "scriptId":"u0"},
    "ff627f7127eb4afb87ab2df30c85a1bd":{
      "scriptId":"u1"},
    "b46407a373914665b508a311f364fb8d":{
      "scriptId":"u2"},
    "d8abc925174c41dd8fd6f814e411cff5":{
      "scriptId":"u3"},
    "0252a9a268be4ef2818280d0717b9ce9":{
      "scriptId":"u4"},
    "e1a4cecc964043958d90ac80512dff73":{
      "scriptId":"u5"},
    "f511c452d4a14dffbe4c0847eddf625d":{
      "scriptId":"u6"},
    "e4e3c5790d0b42c0b001030fb1957b71":{
      "scriptId":"u7"},
    "89525d7147e54c5dbc646879351c7966":{
      "scriptId":"u8"},
    "2003e953eaab478b9d8d70ab743a5247":{
      "scriptId":"u9"},
    "aad78a3a8e8741a2939eafbd5b257208":{
      "scriptId":"u10"},
    "1154c207ed6a488f9598b2fdb9b72373":{
      "scriptId":"u11"},
    "3f7f4fb5082e4988811fc8b4a23851c4":{
      "scriptId":"u12"},
    "1c88e13368e84bbcbed34b0efc9ddd49":{
      "scriptId":"u13"},
    "1c7304ef9d684a2d90cc3f056fa5248c":{
      "scriptId":"u14"},
    "eae9760916f9424c9917598b067074c6":{
      "scriptId":"u15"},
    "ed860859a0a24b1e8f1161c8d549cc71":{
      "scriptId":"u16"},
    "b86996885e3445d58c07b06256ea0921":{
      "scriptId":"u17"},
    "8ca4e3badb92405b8f60f4698388bce7":{
      "scriptId":"u18"},
    "4bc5b73c08db441da45be3fdff6e5471":{
      "scriptId":"u19"},
    "4d2cb1543b524828987bf2d62d9e9caf":{
      "scriptId":"u20"},
    "e9c8fce9811948daa0f207789af7475e":{
      "scriptId":"u21"},
    "c998ed93cbb64e23a970f3ea6ea88915":{
      "scriptId":"u22"},
    "3f37dd473e0449538fb2674829e2b35f":{
      "scriptId":"u23"},
    "cacdd89a528344dfa8058ef91bd846d1":{
      "scriptId":"u24"},
    "7c3ec3da4c834fc4adba428959365fbb":{
      "scriptId":"u25"},
    "d5daf66c73ff4b5b88fb4161a1b6009d":{
      "scriptId":"u26"},
    "8ffb3eb8450d4d33b53b35c5f5425974":{
      "scriptId":"u27"},
    "96f2060315414ec8943fe2e6b11dbc0f":{
      "scriptId":"u28"},
    "d27c5e6343d0416f9a1ff24c5cd07755":{
      "scriptId":"u29"},
    "b57edcd60cdb45808ac39c133eef85de":{
      "scriptId":"u30"},
    "43c3bc78b6284cbd806cc9f40debb658":{
      "scriptId":"u31"},
    "89b019dab1b04cadb3b9a519186fc70b":{
      "scriptId":"u32"},
    "7ff2fccf858348e0892846d382b4a22b":{
      "scriptId":"u33"},
    "dd8eeff987774ec79e928768ccbd9cb7":{
      "scriptId":"u34"},
    "434de672b0bf44639eabacde8cfd3ab3":{
      "scriptId":"u35"},
    "b2df02b8672f4ac39112063cb8770d13":{
      "scriptId":"u36"},
    "d89ee1e4aaf748deba51d948bd82a93b":{
      "scriptId":"u37"},
    "8c186dca97f4419a8dc82135c8a06c87":{
      "scriptId":"u38"},
    "b9d08114d29f43ef9c8270c8391d9375":{
      "scriptId":"u39"},
    "988bbc16994f43a5a9801c799d12121d":{
      "scriptId":"u40"},
    "3db4d053277d4950adc7ecca54e454b0":{
      "scriptId":"u41"},
    "c0742472d40b43a78616f2972fe10445":{
      "scriptId":"u42"},
    "d58ee195d49a4fe1affb4c99fbe76cf0":{
      "scriptId":"u43"},
    "5f7241f5d1bc4a95955fc632febeb8e0":{
      "scriptId":"u44"},
    "0c9a004d348a460e88fc57a4b0d081ae":{
      "scriptId":"u45"},
    "58b87410cbe6483d8d031161fb3059e1":{
      "scriptId":"u46"},
    "b1650839b2614722b6dc5bbe3b3f8745":{
      "scriptId":"u47"},
    "aa3eb74103134c5baffb4073886d6ae4":{
      "scriptId":"u48"},
    "9efb951a56ca4035a5ef65b22050116c":{
      "scriptId":"u49"},
    "a6f1226af4ea44e48806b7d30249acaa":{
      "scriptId":"u50"},
    "d5ce440aeb924762b6bb943b6514a486":{
      "scriptId":"u51"},
    "26a57ef67c81421f98f42f4580afd175":{
      "scriptId":"u52"},
    "58873b1d017c4ee4b8c8b0743853fa92":{
      "scriptId":"u53"},
    "4c7d5c9c54954276a2c059dc7cfb8b14":{
      "scriptId":"u54"},
    "c003438e8e5a4f47af77f3358585338c":{
      "scriptId":"u55"},
    "3e54722d019f4f0a9a9c353c2b607aff":{
      "scriptId":"u56"},
    "6ba61acb5ab240cdba45e19d59f2c7ee":{
      "scriptId":"u57"},
    "50125d6f1cba40b3a51ba06151dee662":{
      "scriptId":"u58"},
    "a1a1882f2a0b4600b0faa0c62f3ee78a":{
      "scriptId":"u59"},
    "eaf4f463a27143f4b1ec6540bb52d93c":{
      "scriptId":"u60"},
    "8481001dce654831997b2ebf2a69c3b4":{
      "scriptId":"u61"},
    "580eb6f0e05748fea435abb395e777e0":{
      "scriptId":"u62"},
    "980ff75177bf45e094f3a844c99e7a16":{
      "scriptId":"u63"},
    "9f59dc992f414b3dbbb3adbd31cfa690":{
      "scriptId":"u64"},
    "6e172fcc2ae84eadb91b1f363591e9f3":{
      "scriptId":"u65"},
    "3d60bfdb5ff648bfb3f5a2b2ec8e7258":{
      "scriptId":"u66"},
    "695c6ef773354715bd3e2ba4322b53e8":{
      "scriptId":"u67"},
    "2bb22ba8362540b691c1f6e77b639e76":{
      "scriptId":"u68"},
    "a3ad6bd33ab348b18c6467eb4431eadf":{
      "scriptId":"u69"},
    "05989f22dd8b46dc96407e8cd4d20936":{
      "scriptId":"u70"},
    "9b58d7ae83f64e4eb63423f8c50f19a7":{
      "scriptId":"u71"},
    "dea28092f60342a0a8d1317774f6f7ff":{
      "scriptId":"u72"},
    "ff1be16ff2a246b0bd9306b5a525003a":{
      "scriptId":"u73"},
    "de7a23b6af4d4697989d7b76b15426c9":{
      "scriptId":"u74"},
    "993eecb3a4734211a6039f32603576d9":{
      "scriptId":"u75"},
    "0323876e740247c18908d3d232a8db93":{
      "scriptId":"u76"},
    "ecfb6f013a184d41a225fb070507604f":{
      "scriptId":"u77"},
    "867729a8470243348094454b10fdb617":{
      "scriptId":"u78"},
    "b39f1eb97e234ed0827a7c5e54730798":{
      "scriptId":"u79"},
    "0a7a11222c8c441394f2d1e9eebd2f4c":{
      "scriptId":"u80"},
    "dc534fcf6b7042fd9ec0668679ddb094":{
      "scriptId":"u81"},
    "84f0fa1044fd4dc3bcd72074f8a32127":{
      "scriptId":"u82"},
    "b911744883744c82b7df8db8022c58c4":{
      "scriptId":"u83"},
    "be4f598434a44025872a977319dde32a":{
      "scriptId":"u84"},
    "07a22a6e80ab4505b413d57d16b42749":{
      "scriptId":"u85"},
    "f750e51569574b2eade174e900ed2975":{
      "scriptId":"u86"},
    "6efd079654834f41a6c84867d52e8d03":{
      "scriptId":"u87"},
    "7f6fd905d89d4bdd9b168a2372329160":{
      "scriptId":"u88"},
    "6589043b5b3d4d079821d392cf2bd6d4":{
      "scriptId":"u89"},
    "ab4342f4b43a46bfad28d03796aa2843":{
      "scriptId":"u90"},
    "649c0478afe5418386e599518b1c9686":{
      "scriptId":"u91"},
    "a306afd8b1b3404ebcb3c6d492e7b3a0":{
      "scriptId":"u92"},
    "5d68bdf2e45b45919eca9ad78fafa6f7":{
      "scriptId":"u93"},
    "69ce1b7884cf4cb7bc32c3c77cf70799":{
      "scriptId":"u94"},
    "945e1da61b1f4380978cabac7fb1c178":{
      "scriptId":"u95"},
    "b92dc68a25574cde956b9af5b6cc261c":{
      "scriptId":"u96"},
    "fed01872b3ea45e790da2dd9fec692d8":{
      "scriptId":"u97"},
    "4e34bbeb294a4bb99909784c5da7ba1d":{
      "scriptId":"u98"},
    "ebb4f5e62fb7474eba510f9603d7189d":{
      "scriptId":"u99"},
    "6c21888b226942bc8bb9053d79b3ec4c":{
      "scriptId":"u100"},
    "49de96fd0b9a497492248e23444187de":{
      "scriptId":"u101"},
    "1bc92a89f08546c69a8c9de1876dfe95":{
      "scriptId":"u102"},
    "abf4c63c5b684f719cd9b3a7e1ee4690":{
      "scriptId":"u103"}}});