$axure.loadCurrentPage({
  "url":"消费者评价.html",
  "generationDate":new Date(1413021311233.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a42f3355e3c549c3964c888dc61ac29f",
    "type":"Axure:Page",
    "name":"消费者评价",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c1666168c94e3baf1d3bfe07423490",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":970,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff627f7127eb4afb87ab2df30c85a1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":970,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u10.png"}},
{
          "id":"b46407a373914665b508a311f364fb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":0,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8abc925174c41dd8fd6f814e411cff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":0,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"0252a9a268be4ef2818280d0717b9ce9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":100,
              "y":67},
            "size":{
              "width":768,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a4cecc964043958d90ac80512dff73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":100,
                  "y":67},
                "size":{
                  "width":768,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u4.png"}},
{
          "id":"f511c452d4a14dffbe4c0847eddf625d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":868,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e3c5790d0b42c0b001030fb1957b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":868,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"89525d7147e54c5dbc646879351c7966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":608},
            "size":{
              "width":970,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2003e953eaab478b9d8d70ab743a5247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":608},
                "size":{
                  "width":970,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u36.png"}},
{
          "id":"aad78a3a8e8741a2939eafbd5b257208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":970,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1154c207ed6a488f9598b2fdb9b72373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":617},
                "size":{
                  "width":970,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u38.png"}},
{
          "id":"3f7f4fb5082e4988811fc8b4a23851c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c88e13368e84bbcbed34b0efc9ddd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c7304ef9d684a2d90cc3f056fa5248c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae9760916f9424c9917598b067074c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed860859a0a24b1e8f1161c8d549cc71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":444,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86996885e3445d58c07b06256ea0921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":444,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca4e3badb92405b8f60f4698388bce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":600,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc5b73c08db441da45be3fdff6e5471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":600,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2cb1543b524828987bf2d62d9e9caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":180,
              "y":670},
            "size":{
              "width":730,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c8fce9811948daa0f207789af7475e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":670},
                "size":{
                  "width":730,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"988bbc16994f43a5a9801c799d12121d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":95},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3db4d053277d4950adc7ecca54e454b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":95},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26eece99fd6d43aca84a3fa6260624e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":257,
              "y":90},
            "size":{
              "width":145,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa4020c55d64d4dac57f75ec1363af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":257,
                  "y":90},
                "size":{
                  "width":145,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c31e47c70814f12a81f70df5a98355d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":113},
            "size":{
              "width":570,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bcd03196da44191a81c489a83aa66e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":113},
                "size":{
                  "width":570,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u26.png"}},
{
          "id":"6c4e0f18015d42588fc3d21f1018dcaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":253,
              "y":251},
            "size":{
              "width":99,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"764b491f3ffe46fba8a92d8a077cd53c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":253,
                  "y":251},
                "size":{
                  "width":99,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u28.png"}},
{
          "id":"b06ae73baa04479cb9edde843695954c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":362,
              "y":251},
            "size":{
              "width":99,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1141047d8db47e28c185883d94bd5e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":362,
                  "y":251},
                "size":{
                  "width":99,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u30.png"}},
{
          "id":"8536000be5b34a3cbe4faaafe50591ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":477,
              "y":251},
            "size":{
              "width":99,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71f40a1ffdd040a89a507d1d8bf2846c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":477,
                  "y":251},
                "size":{
                  "width":99,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u30.png"}},
{
          "id":"0d674d6d07ce4c68a8889dacb7f42f6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":591,
              "y":251},
            "size":{
              "width":99,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3edbf1b74ede4a21be36f7456128dc33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":591,
                  "y":251},
                "size":{
                  "width":99,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u30.png"}},
{
          "id":"3366776b1d724963a3d787500dfb6d06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":705,
              "y":251},
            "size":{
              "width":99,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d25031a95946ed843ca7a49b434e0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":705,
                  "y":251},
                "size":{
                  "width":99,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u30.png"}},
{
          "id":"0c3cdaaa23e44549b47db71a98f20d65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":254,
              "y":284},
            "size":{
              "width":138,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4eaeab269994de0a6c587a754133fb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":284},
                "size":{
                  "width":138,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d144b30c80fc43a19b0a1a030f4a7f48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":716,
              "y":283},
            "size":{
              "width":76,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f1910b5fdf466987ac5fbeb2a8c12c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":716,
                  "y":283},
                "size":{
                  "width":76,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u40.png"}},
{
          "id":"15204e0792634ddfa39a23885715b888",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":254,
              "y":310},
            "size":{
              "width":538,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392a8c8a19214aea919d00eeedd6644e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":310},
                "size":{
                  "width":538,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b10f5ca9430748d2b3d725665a191c79",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":331},
            "size":{
              "width":550,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/消费者评价/u44_line.png"}},
{
          "id":"a1907a1dd4464350aefa8b33ad2bbc08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":734,
              "y":311},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2077ba1bccd74b85977a9ce731a1c076",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":734,
                  "y":311},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u45.png"}},
{
          "id":"b2d050f4dbdb4d6f9881d47e5fb52876",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":254,
              "y":342},
            "size":{
              "width":138,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c71c099c8a664dfabb407d9eca195ba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":342},
                "size":{
                  "width":138,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27689801a8ac437a8f034c60e9590177",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":716,
              "y":341},
            "size":{
              "width":76,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b0b9f62640c4f8184a10745548d8482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":716,
                  "y":341},
                "size":{
                  "width":76,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u40.png"}},
{
          "id":"c0b861cd1a7a43a5b0fe88b512c6557d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":254,
              "y":368},
            "size":{
              "width":538,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edc01c65b397435088b8cc45a753f68c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":368},
                "size":{
                  "width":538,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67423c7558aa40df92daf9cc0c41a3ae",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":389},
            "size":{
              "width":550,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/消费者评价/u44_line.png"}},
{
          "id":"69166b69627545eebe8c4006dc8c0691",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":254,
              "y":410},
            "size":{
              "width":138,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1711dba891d5479494c0447a921f2373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":410},
                "size":{
                  "width":138,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65cdf2ff46854db685fe0596fb56ff31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":716,
              "y":409},
            "size":{
              "width":76,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a8fb95baa6f49548ccd9133f67dccd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":716,
                  "y":409},
                "size":{
                  "width":76,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u40.png"}},
{
          "id":"ddad5c0f907d474ab9799bd1ad8dde8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":254,
              "y":436},
            "size":{
              "width":538,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"398b8dedeaee42778c23fe3dc5b8b812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":436},
                "size":{
                  "width":538,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d187929ba2064861a0aa644783f0db21",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":251,
              "y":507},
            "size":{
              "width":550,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/消费者评价/u44_line.png"}},
{
          "id":"ec8bbc04165a43358ece74fea23b511e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":734,
              "y":372},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cccfa4a304e744ab92f6882ba6222e84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":734,
                  "y":372},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u45.png"}},
{
          "id":"1e02eaf2de79419f93cb480e3a4ffac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":734,
              "y":439},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6ce81aa409b4d7385f26cddc28fe4bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":734,
                  "y":439},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u63.png"}},
{
          "id":"530405f0746c4964ad865b685b8e75d6",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":468},
            "size":{
              "width":478,
              "height":38}},
          "adaptiveStyles":{
}},
{
          "id":"2964f7bcbeb94739b55fb18ba49ad724",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":734,
              "y":486},
            "size":{
              "width":58,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1d0930a1b9a42718af0163b7534aaf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":734,
                  "y":486},
                "size":{
                  "width":58,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u66.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "03c1666168c94e3baf1d3bfe07423490":{
      "scriptId":"u0"},
    "ff627f7127eb4afb87ab2df30c85a1bd":{
      "scriptId":"u1"},
    "b46407a373914665b508a311f364fb8d":{
      "scriptId":"u2"},
    "d8abc925174c41dd8fd6f814e411cff5":{
      "scriptId":"u3"},
    "0252a9a268be4ef2818280d0717b9ce9":{
      "scriptId":"u4"},
    "e1a4cecc964043958d90ac80512dff73":{
      "scriptId":"u5"},
    "f511c452d4a14dffbe4c0847eddf625d":{
      "scriptId":"u6"},
    "e4e3c5790d0b42c0b001030fb1957b71":{
      "scriptId":"u7"},
    "89525d7147e54c5dbc646879351c7966":{
      "scriptId":"u8"},
    "2003e953eaab478b9d8d70ab743a5247":{
      "scriptId":"u9"},
    "aad78a3a8e8741a2939eafbd5b257208":{
      "scriptId":"u10"},
    "1154c207ed6a488f9598b2fdb9b72373":{
      "scriptId":"u11"},
    "3f7f4fb5082e4988811fc8b4a23851c4":{
      "scriptId":"u12"},
    "1c88e13368e84bbcbed34b0efc9ddd49":{
      "scriptId":"u13"},
    "1c7304ef9d684a2d90cc3f056fa5248c":{
      "scriptId":"u14"},
    "eae9760916f9424c9917598b067074c6":{
      "scriptId":"u15"},
    "ed860859a0a24b1e8f1161c8d549cc71":{
      "scriptId":"u16"},
    "b86996885e3445d58c07b06256ea0921":{
      "scriptId":"u17"},
    "8ca4e3badb92405b8f60f4698388bce7":{
      "scriptId":"u18"},
    "4bc5b73c08db441da45be3fdff6e5471":{
      "scriptId":"u19"},
    "4d2cb1543b524828987bf2d62d9e9caf":{
      "scriptId":"u20"},
    "e9c8fce9811948daa0f207789af7475e":{
      "scriptId":"u21"},
    "988bbc16994f43a5a9801c799d12121d":{
      "scriptId":"u22"},
    "3db4d053277d4950adc7ecca54e454b0":{
      "scriptId":"u23"},
    "26eece99fd6d43aca84a3fa6260624e1":{
      "scriptId":"u24"},
    "2aa4020c55d64d4dac57f75ec1363af4":{
      "scriptId":"u25"},
    "2c31e47c70814f12a81f70df5a98355d":{
      "scriptId":"u26"},
    "8bcd03196da44191a81c489a83aa66e7":{
      "scriptId":"u27"},
    "6c4e0f18015d42588fc3d21f1018dcaa":{
      "scriptId":"u28"},
    "764b491f3ffe46fba8a92d8a077cd53c":{
      "scriptId":"u29"},
    "b06ae73baa04479cb9edde843695954c":{
      "scriptId":"u30"},
    "e1141047d8db47e28c185883d94bd5e7":{
      "scriptId":"u31"},
    "8536000be5b34a3cbe4faaafe50591ff":{
      "scriptId":"u32"},
    "71f40a1ffdd040a89a507d1d8bf2846c":{
      "scriptId":"u33"},
    "0d674d6d07ce4c68a8889dacb7f42f6f":{
      "scriptId":"u34"},
    "3edbf1b74ede4a21be36f7456128dc33":{
      "scriptId":"u35"},
    "3366776b1d724963a3d787500dfb6d06":{
      "scriptId":"u36"},
    "00d25031a95946ed843ca7a49b434e0d":{
      "scriptId":"u37"},
    "0c3cdaaa23e44549b47db71a98f20d65":{
      "scriptId":"u38"},
    "d4eaeab269994de0a6c587a754133fb0":{
      "scriptId":"u39"},
    "d144b30c80fc43a19b0a1a030f4a7f48":{
      "scriptId":"u40"},
    "e7f1910b5fdf466987ac5fbeb2a8c12c":{
      "scriptId":"u41"},
    "15204e0792634ddfa39a23885715b888":{
      "scriptId":"u42"},
    "392a8c8a19214aea919d00eeedd6644e":{
      "scriptId":"u43"},
    "b10f5ca9430748d2b3d725665a191c79":{
      "scriptId":"u44"},
    "a1907a1dd4464350aefa8b33ad2bbc08":{
      "scriptId":"u45"},
    "2077ba1bccd74b85977a9ce731a1c076":{
      "scriptId":"u46"},
    "b2d050f4dbdb4d6f9881d47e5fb52876":{
      "scriptId":"u47"},
    "c71c099c8a664dfabb407d9eca195ba2":{
      "scriptId":"u48"},
    "27689801a8ac437a8f034c60e9590177":{
      "scriptId":"u49"},
    "0b0b9f62640c4f8184a10745548d8482":{
      "scriptId":"u50"},
    "c0b861cd1a7a43a5b0fe88b512c6557d":{
      "scriptId":"u51"},
    "edc01c65b397435088b8cc45a753f68c":{
      "scriptId":"u52"},
    "67423c7558aa40df92daf9cc0c41a3ae":{
      "scriptId":"u53"},
    "69166b69627545eebe8c4006dc8c0691":{
      "scriptId":"u54"},
    "1711dba891d5479494c0447a921f2373":{
      "scriptId":"u55"},
    "65cdf2ff46854db685fe0596fb56ff31":{
      "scriptId":"u56"},
    "4a8fb95baa6f49548ccd9133f67dccd8":{
      "scriptId":"u57"},
    "ddad5c0f907d474ab9799bd1ad8dde8b":{
      "scriptId":"u58"},
    "398b8dedeaee42778c23fe3dc5b8b812":{
      "scriptId":"u59"},
    "d187929ba2064861a0aa644783f0db21":{
      "scriptId":"u60"},
    "ec8bbc04165a43358ece74fea23b511e":{
      "scriptId":"u61"},
    "cccfa4a304e744ab92f6882ba6222e84":{
      "scriptId":"u62"},
    "1e02eaf2de79419f93cb480e3a4ffac2":{
      "scriptId":"u63"},
    "f6ce81aa409b4d7385f26cddc28fe4bb":{
      "scriptId":"u64"},
    "530405f0746c4964ad865b685b8e75d6":{
      "scriptId":"u65"},
    "2964f7bcbeb94739b55fb18ba49ad724":{
      "scriptId":"u66"},
    "a1d0930a1b9a42718af0163b7534aaf8":{
      "scriptId":"u67"}}});