$axure.loadCurrentPage({
  "url":"添加商品.html",
  "generationDate":new Date(1413021311090.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8cbac720687449e0a75229b1facbf190",
    "type":"Axure:Page",
    "name":"添加商品",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c1666168c94e3baf1d3bfe07423490",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":970,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff627f7127eb4afb87ab2df30c85a1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":970,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u0.png"}},
{
          "id":"b46407a373914665b508a311f364fb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":0,
              "y":67},
            "size":{
              "width":100,
              "height":914},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8abc925174c41dd8fd6f814e411cff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":0,
                  "y":67},
                "size":{
                  "width":100,
                  "height":914},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u2.png"}},
{
          "id":"0252a9a268be4ef2818280d0717b9ce9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":100,
              "y":67},
            "size":{
              "width":768,
              "height":914},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a4cecc964043958d90ac80512dff73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":100,
                  "y":67},
                "size":{
                  "width":768,
                  "height":914},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u4.png"}},
{
          "id":"f511c452d4a14dffbe4c0847eddf625d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":868,
              "y":67},
            "size":{
              "width":100,
              "height":914},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e3c5790d0b42c0b001030fb1957b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":868,
                  "y":67},
                "size":{
                  "width":100,
                  "height":914},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u2.png"}},
{
          "id":"89525d7147e54c5dbc646879351c7966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":981},
            "size":{
              "width":970,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2003e953eaab478b9d8d70ab743a5247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":981},
                "size":{
                  "width":970,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u36.png"}},
{
          "id":"aad78a3a8e8741a2939eafbd5b257208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":990},
            "size":{
              "width":970,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1154c207ed6a488f9598b2fdb9b72373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":990},
                "size":{
                  "width":970,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u38.png"}},
{
          "id":"3f7f4fb5082e4988811fc8b4a23851c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":1002},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c88e13368e84bbcbed34b0efc9ddd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":1002},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c7304ef9d684a2d90cc3f056fa5248c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":1002},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae9760916f9424c9917598b067074c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":1002},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed860859a0a24b1e8f1161c8d549cc71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":444,
              "y":1002},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86996885e3445d58c07b06256ea0921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":444,
                  "y":1002},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca4e3badb92405b8f60f4698388bce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":600,
              "y":1002},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc5b73c08db441da45be3fdff6e5471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":600,
                  "y":1002},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2cb1543b524828987bf2d62d9e9caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":180,
              "y":1043},
            "size":{
              "width":730,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c8fce9811948daa0f207789af7475e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":1043},
                "size":{
                  "width":730,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c998ed93cbb64e23a970f3ea6ea88915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":105},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f37dd473e0449538fb2674829e2b35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":105},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cacdd89a528344dfa8058ef91bd846d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":130},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3ec3da4c834fc4adba428959365fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":130},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5daf66c73ff4b5b88fb4161a1b6009d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":156},
            "size":{
              "width":80,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffb3eb8450d4d33b53b35c5f5425974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":156},
                "size":{
                  "width":80,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f2060315414ec8943fe2e6b11dbc0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":181},
            "size":{
              "width":90,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d27c5e6343d0416f9a1ff24c5cd07755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":181},
                "size":{
                  "width":90,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26eece99fd6d43aca84a3fa6260624e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":262,
              "y":84},
            "size":{
              "width":145,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa4020c55d64d4dac57f75ec1363af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":262,
                  "y":84},
                "size":{
                  "width":145,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40497f502fae4039b2b2b1913dcc4607",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":202},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a418f863ee544ab8bd53abefc67d9248",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":202},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb4b9ea6af2e47dcb4c094a1453d8a7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":262,
              "y":272},
            "size":{
              "width":118,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37f812d92a0b4a56a885f8bb53f6e7e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":262,
                  "y":272},
                "size":{
                  "width":118,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81e67b462d8b4e0c9814cb3c914057e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":138,
              "y":223},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aa86b6ec9974aad9f073e6282e95962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":223},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adebc16548c942c4aeb61b97998ae2b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":112},
            "size":{
              "width":238,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ad1671b01645d7977c91ee8ff853a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":112},
                "size":{
                  "width":238,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品/u38.png"}},
{
          "id":"80c22459dc664ae49b19b93001af6b41",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":272},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a74a2b5f9cd94c3196b3b65de8120f23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":396,
                  "y":272},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"49d91459d4324380806d61c4d84c95d2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":102},
            "size":{
              "width":564,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/店铺信息/u41_line.png"}},
{
          "id":"53ecab5bd21040c3bda4deed0235322d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":540,
              "y":270},
            "size":{
              "width":118,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dce44b445f144798d611b2be1b36e15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":540,
                  "y":270},
                "size":{
                  "width":118,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd19599c5ec94959931b7a5cef83bc5b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":112},
            "size":{
              "width":238,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c22e6a73deea47c1a5299d7b9db36a0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":112},
                "size":{
                  "width":238,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品/u38.png"}},
{
          "id":"ebf3da5bcf734e30bdae0121e1240c83",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":270},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3c725b31c19455a8e28a4fb4e9ecefa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":674,
                  "y":270},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e39af1586a3249e899beb2b93ffb5b39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":262,
              "y":466},
            "size":{
              "width":118,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83fb19a59aad4350b29b5a8ed2095cb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":262,
                  "y":466},
                "size":{
                  "width":118,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78c0308f4f344321a05f1d718ef6a605",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":308},
            "size":{
              "width":238,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68762f4d1d304f069f72593b1af5ebbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":308},
                "size":{
                  "width":238,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品/u38.png"}},
{
          "id":"1a50a2dfed774527adf40eb312a64e4e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":466},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a638642631754e1eaae711f9fb23560f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":396,
                  "y":466},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6841ed4e82d24078845434d5b16f8422",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":540,
              "y":466},
            "size":{
              "width":118,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a71b42454b9e41ec800494cba0559d95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":540,
                  "y":466},
                "size":{
                  "width":118,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a08e0f3e1bb548af946dfde28cbcd830",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":308},
            "size":{
              "width":238,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c20d6a539f154e1da993e2a3cb6cf7f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":308},
                "size":{
                  "width":238,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品/u38.png"}},
{
          "id":"9e9193ff1e544bc8bf80998f5c49e534",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":466},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce042c47799b4d32a93a8fa3fc181fa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":674,
                  "y":466},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"89669ea068494e31b3f61ca018571556",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":746,
              "y":81},
            "size":{
              "width":80,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60417410c06d4834b23a7fc0970f7406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":746,
                  "y":81},
                "size":{
                  "width":80,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 sp 置于顶层",
                      "objectsToFades":[{
                          "objectPath":["1694fed8e85946d8a5d7bac4dbb19ebb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"front"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/店铺信息/u97.png"}},
{
          "id":"c7e801646932476da334991703c2ad8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":262,
              "y":650},
            "size":{
              "width":118,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0c54258160e456ba0c16b403b109e02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":262,
                  "y":650},
                "size":{
                  "width":118,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b98beb767a674fba8802f68e8dd44eaa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":492},
            "size":{
              "width":238,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a82eac10d945467fb2beaa727749b129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":492},
                "size":{
                  "width":238,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品/u38.png"}},
{
          "id":"bb9545282f984422abce86320c74be6f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":650},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c44543e6c254627b2ac752cc4f33c2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":396,
                  "y":650},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9ce5cb6579e644b6ae8a5d1fd6c37480",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":540,
              "y":650},
            "size":{
              "width":118,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48b1208ded874de3852f4431862942ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":540,
                  "y":650},
                "size":{
                  "width":118,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6054da5cc134e2c9d332a8e37654d23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":492},
            "size":{
              "width":238,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50353e7bf9a646808b80103e1b52821d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":492},
                "size":{
                  "width":238,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品/u38.png"}},
{
          "id":"21e21c82bae644d29ed446998012d1db",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":650},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba008d087829458dad75960906eb05ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":674,
                  "y":650},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1db4424bab5c431d973b17de4a9d6e09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":262,
              "y":834},
            "size":{
              "width":118,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d101146f782e4c958f4d9d8cc4e1e66c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":262,
                  "y":834},
                "size":{
                  "width":118,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdced900384e445bbf4094566cb4e0a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":676},
            "size":{
              "width":238,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10d59831e4314b40ba3d0f5c26056d31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":676},
                "size":{
                  "width":238,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品/u38.png"}},
{
          "id":"38bdd651242149e89bcc80552657c36a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":834},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6332d1eb74242c8806e40fb60a96abc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":396,
                  "y":834},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"38243ab54b464e339ca98d9798d67a36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":540,
              "y":834},
            "size":{
              "width":118,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30b8dcbf27e348af9616fa11ace22631",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":540,
                  "y":834},
                "size":{
                  "width":118,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff0d96a535cb4deabfa5dc91b68dfd1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":676},
            "size":{
              "width":238,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c24a3a3da2084256abf161f3aea27867",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":676},
                "size":{
                  "width":238,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加商品/u38.png"}},
{
          "id":"6450843d5dd6456eab898e64b4737056",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":834},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96f2a75b62064a93b71d0bcb8b678051",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":674,
                  "y":834},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1694fed8e85946d8a5d7bac4dbb19ebb",
          "label":"sp",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":290,
              "y":131},
            "size":{
              "width":470,
              "height":459},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c8cc37f1f8c947f1b7415cac00311daf",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e4dd085b796241e2afa4876ee663d2a7",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":470,
                      "height":460}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e3b6224c61c14799b7ff580b45ab9a78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":470,
                          "height":460}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/添加商品/u88.png"}},
{
                  "id":"04b50c99f52348ed856bc11d51d0ce9d",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"bold",
                    "location":{
                      "x":42,
                      "y":9},
                    "size":{
                      "width":145,
                      "height":21},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae16ffec69284e508db97c7a05d65df6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"bold",
                        "location":{
                          "x":42,
                          "y":9},
                        "size":{
                          "width":145,
                          "height":21},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aa12576f09044f5c9b2c26b6f4ddd397",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":50},
                    "size":{
                      "width":275,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"fefd1b5c47e34de690cfa0f08de4e167",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":54},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39f439a489704386a39a3a3d381d172c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":54},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6d4272bb499d44c0bf68cb916b12997a",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":77},
                    "size":{
                      "width":275,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"9c18a33849ee43d6a5ee53c4d027a785",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":81},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa5c1979b73c4103a3b94fc93dc0208d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":81},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"df8ac29088e148c0a086665e942a1e7a",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":103},
                    "size":{
                      "width":275,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"0dbce926c9654932a50e9772d6989f24",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":107},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d493009595f7477e8ba62b354852944e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":107},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4676122d73e649188f15e3823e64c68f",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":159},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c8a222fd0894be4a3390273335842bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":159},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"08a7233873ba45a7823fa308008f2709",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":185,
                      "y":159},
                    "size":{
                      "width":275,
                      "height":162}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"673ca83113324fd3b8c7e2367e928d53",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":185,
                          "y":159},
                        "size":{
                          "width":275,
                          "height":162}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺信息/u56.png"}},
{
                  "id":"f1d5c2e8465440dba58aedff9747b494",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC00},
                    "location":{
                      "x":160,
                      "y":397},
                    "size":{
                      "width":130,
                      "height":40},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a12b1e4afdb43bb8b0b48575771aedb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFCC00},
                        "location":{
                          "x":160,
                          "y":397},
                        "size":{
                          "width":130,
                          "height":40},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/店铺信息/u37.png"}},
{
                  "id":"bb65fa4e75664be48a1c8c80766e1c90",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":361},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b5b85a8ce4b4c83a27fe345d6d2dad1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":361},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"87d2307686b14802b8a8f8acf379bf46",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":361},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4214ae7774df40d987fccbbab803a08d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":200,
                          "y":361},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"007240a3da904060a09e25fb278d12bc",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":270,
                      "y":361},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e94cf04d85f48f5ade6e93c7b829070",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":270,
                          "y":361},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"a30abce71843498e92639f5820c4cffe",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"bold",
                    "location":{
                      "x":72,
                      "y":136},
                    "size":{
                      "width":140,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15b546440b3b47bd8cf922019b56b597",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"bold",
                        "location":{
                          "x":72,
                          "y":136},
                        "size":{
                          "width":140,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"784ea6c7ffa743c1b2443e55b27183a3",
                  "label":"",
                  "parentDynamicPanel":"1694fed8e85946d8a5d7bac4dbb19ebb",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":185,
                      "y":135},
                    "size":{
                      "width":275,
                      "height":22}},
                  "adaptiveStyles":{
}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "03c1666168c94e3baf1d3bfe07423490":{
      "scriptId":"u0"},
    "ff627f7127eb4afb87ab2df30c85a1bd":{
      "scriptId":"u1"},
    "b46407a373914665b508a311f364fb8d":{
      "scriptId":"u2"},
    "d8abc925174c41dd8fd6f814e411cff5":{
      "scriptId":"u3"},
    "0252a9a268be4ef2818280d0717b9ce9":{
      "scriptId":"u4"},
    "e1a4cecc964043958d90ac80512dff73":{
      "scriptId":"u5"},
    "f511c452d4a14dffbe4c0847eddf625d":{
      "scriptId":"u6"},
    "e4e3c5790d0b42c0b001030fb1957b71":{
      "scriptId":"u7"},
    "89525d7147e54c5dbc646879351c7966":{
      "scriptId":"u8"},
    "2003e953eaab478b9d8d70ab743a5247":{
      "scriptId":"u9"},
    "aad78a3a8e8741a2939eafbd5b257208":{
      "scriptId":"u10"},
    "1154c207ed6a488f9598b2fdb9b72373":{
      "scriptId":"u11"},
    "3f7f4fb5082e4988811fc8b4a23851c4":{
      "scriptId":"u12"},
    "1c88e13368e84bbcbed34b0efc9ddd49":{
      "scriptId":"u13"},
    "1c7304ef9d684a2d90cc3f056fa5248c":{
      "scriptId":"u14"},
    "eae9760916f9424c9917598b067074c6":{
      "scriptId":"u15"},
    "ed860859a0a24b1e8f1161c8d549cc71":{
      "scriptId":"u16"},
    "b86996885e3445d58c07b06256ea0921":{
      "scriptId":"u17"},
    "8ca4e3badb92405b8f60f4698388bce7":{
      "scriptId":"u18"},
    "4bc5b73c08db441da45be3fdff6e5471":{
      "scriptId":"u19"},
    "4d2cb1543b524828987bf2d62d9e9caf":{
      "scriptId":"u20"},
    "e9c8fce9811948daa0f207789af7475e":{
      "scriptId":"u21"},
    "c998ed93cbb64e23a970f3ea6ea88915":{
      "scriptId":"u22"},
    "3f37dd473e0449538fb2674829e2b35f":{
      "scriptId":"u23"},
    "cacdd89a528344dfa8058ef91bd846d1":{
      "scriptId":"u24"},
    "7c3ec3da4c834fc4adba428959365fbb":{
      "scriptId":"u25"},
    "d5daf66c73ff4b5b88fb4161a1b6009d":{
      "scriptId":"u26"},
    "8ffb3eb8450d4d33b53b35c5f5425974":{
      "scriptId":"u27"},
    "96f2060315414ec8943fe2e6b11dbc0f":{
      "scriptId":"u28"},
    "d27c5e6343d0416f9a1ff24c5cd07755":{
      "scriptId":"u29"},
    "26eece99fd6d43aca84a3fa6260624e1":{
      "scriptId":"u30"},
    "2aa4020c55d64d4dac57f75ec1363af4":{
      "scriptId":"u31"},
    "40497f502fae4039b2b2b1913dcc4607":{
      "scriptId":"u32"},
    "a418f863ee544ab8bd53abefc67d9248":{
      "scriptId":"u33"},
    "cb4b9ea6af2e47dcb4c094a1453d8a7d":{
      "scriptId":"u34"},
    "37f812d92a0b4a56a885f8bb53f6e7e8":{
      "scriptId":"u35"},
    "81e67b462d8b4e0c9814cb3c914057e8":{
      "scriptId":"u36"},
    "0aa86b6ec9974aad9f073e6282e95962":{
      "scriptId":"u37"},
    "adebc16548c942c4aeb61b97998ae2b1":{
      "scriptId":"u38"},
    "d1ad1671b01645d7977c91ee8ff853a4":{
      "scriptId":"u39"},
    "80c22459dc664ae49b19b93001af6b41":{
      "scriptId":"u40"},
    "a74a2b5f9cd94c3196b3b65de8120f23":{
      "scriptId":"u41"},
    "49d91459d4324380806d61c4d84c95d2":{
      "scriptId":"u42"},
    "53ecab5bd21040c3bda4deed0235322d":{
      "scriptId":"u43"},
    "5dce44b445f144798d611b2be1b36e15":{
      "scriptId":"u44"},
    "bd19599c5ec94959931b7a5cef83bc5b":{
      "scriptId":"u45"},
    "c22e6a73deea47c1a5299d7b9db36a0d":{
      "scriptId":"u46"},
    "ebf3da5bcf734e30bdae0121e1240c83":{
      "scriptId":"u47"},
    "b3c725b31c19455a8e28a4fb4e9ecefa":{
      "scriptId":"u48"},
    "e39af1586a3249e899beb2b93ffb5b39":{
      "scriptId":"u49"},
    "83fb19a59aad4350b29b5a8ed2095cb8":{
      "scriptId":"u50"},
    "78c0308f4f344321a05f1d718ef6a605":{
      "scriptId":"u51"},
    "68762f4d1d304f069f72593b1af5ebbf":{
      "scriptId":"u52"},
    "1a50a2dfed774527adf40eb312a64e4e":{
      "scriptId":"u53"},
    "a638642631754e1eaae711f9fb23560f":{
      "scriptId":"u54"},
    "6841ed4e82d24078845434d5b16f8422":{
      "scriptId":"u55"},
    "a71b42454b9e41ec800494cba0559d95":{
      "scriptId":"u56"},
    "a08e0f3e1bb548af946dfde28cbcd830":{
      "scriptId":"u57"},
    "c20d6a539f154e1da993e2a3cb6cf7f1":{
      "scriptId":"u58"},
    "9e9193ff1e544bc8bf80998f5c49e534":{
      "scriptId":"u59"},
    "ce042c47799b4d32a93a8fa3fc181fa9":{
      "scriptId":"u60"},
    "89669ea068494e31b3f61ca018571556":{
      "scriptId":"u61"},
    "60417410c06d4834b23a7fc0970f7406":{
      "scriptId":"u62"},
    "c7e801646932476da334991703c2ad8f":{
      "scriptId":"u63"},
    "c0c54258160e456ba0c16b403b109e02":{
      "scriptId":"u64"},
    "b98beb767a674fba8802f68e8dd44eaa":{
      "scriptId":"u65"},
    "a82eac10d945467fb2beaa727749b129":{
      "scriptId":"u66"},
    "bb9545282f984422abce86320c74be6f":{
      "scriptId":"u67"},
    "8c44543e6c254627b2ac752cc4f33c2d":{
      "scriptId":"u68"},
    "9ce5cb6579e644b6ae8a5d1fd6c37480":{
      "scriptId":"u69"},
    "48b1208ded874de3852f4431862942ac":{
      "scriptId":"u70"},
    "c6054da5cc134e2c9d332a8e37654d23":{
      "scriptId":"u71"},
    "50353e7bf9a646808b80103e1b52821d":{
      "scriptId":"u72"},
    "21e21c82bae644d29ed446998012d1db":{
      "scriptId":"u73"},
    "ba008d087829458dad75960906eb05ee":{
      "scriptId":"u74"},
    "1db4424bab5c431d973b17de4a9d6e09":{
      "scriptId":"u75"},
    "d101146f782e4c958f4d9d8cc4e1e66c":{
      "scriptId":"u76"},
    "cdced900384e445bbf4094566cb4e0a5":{
      "scriptId":"u77"},
    "10d59831e4314b40ba3d0f5c26056d31":{
      "scriptId":"u78"},
    "38bdd651242149e89bcc80552657c36a":{
      "scriptId":"u79"},
    "b6332d1eb74242c8806e40fb60a96abc":{
      "scriptId":"u80"},
    "38243ab54b464e339ca98d9798d67a36":{
      "scriptId":"u81"},
    "30b8dcbf27e348af9616fa11ace22631":{
      "scriptId":"u82"},
    "ff0d96a535cb4deabfa5dc91b68dfd1c":{
      "scriptId":"u83"},
    "c24a3a3da2084256abf161f3aea27867":{
      "scriptId":"u84"},
    "6450843d5dd6456eab898e64b4737056":{
      "scriptId":"u85"},
    "96f2a75b62064a93b71d0bcb8b678051":{
      "scriptId":"u86"},
    "1694fed8e85946d8a5d7bac4dbb19ebb":{
      "scriptId":"u87"},
    "e4dd085b796241e2afa4876ee663d2a7":{
      "scriptId":"u88"},
    "e3b6224c61c14799b7ff580b45ab9a78":{
      "scriptId":"u89"},
    "04b50c99f52348ed856bc11d51d0ce9d":{
      "scriptId":"u90"},
    "ae16ffec69284e508db97c7a05d65df6":{
      "scriptId":"u91"},
    "aa12576f09044f5c9b2c26b6f4ddd397":{
      "scriptId":"u92"},
    "fefd1b5c47e34de690cfa0f08de4e167":{
      "scriptId":"u93"},
    "39f439a489704386a39a3a3d381d172c":{
      "scriptId":"u94"},
    "6d4272bb499d44c0bf68cb916b12997a":{
      "scriptId":"u95"},
    "9c18a33849ee43d6a5ee53c4d027a785":{
      "scriptId":"u96"},
    "fa5c1979b73c4103a3b94fc93dc0208d":{
      "scriptId":"u97"},
    "df8ac29088e148c0a086665e942a1e7a":{
      "scriptId":"u98"},
    "0dbce926c9654932a50e9772d6989f24":{
      "scriptId":"u99"},
    "d493009595f7477e8ba62b354852944e":{
      "scriptId":"u100"},
    "4676122d73e649188f15e3823e64c68f":{
      "scriptId":"u101"},
    "8c8a222fd0894be4a3390273335842bc":{
      "scriptId":"u102"},
    "08a7233873ba45a7823fa308008f2709":{
      "scriptId":"u103"},
    "673ca83113324fd3b8c7e2367e928d53":{
      "scriptId":"u104"},
    "f1d5c2e8465440dba58aedff9747b494":{
      "scriptId":"u105"},
    "5a12b1e4afdb43bb8b0b48575771aedb":{
      "scriptId":"u106"},
    "bb65fa4e75664be48a1c8c80766e1c90":{
      "scriptId":"u107"},
    "5b5b85a8ce4b4c83a27fe345d6d2dad1":{
      "scriptId":"u108"},
    "87d2307686b14802b8a8f8acf379bf46":{
      "scriptId":"u109"},
    "4214ae7774df40d987fccbbab803a08d":{
      "scriptId":"u110"},
    "007240a3da904060a09e25fb278d12bc":{
      "scriptId":"u111"},
    "5e94cf04d85f48f5ade6e93c7b829070":{
      "scriptId":"u112"},
    "a30abce71843498e92639f5820c4cffe":{
      "scriptId":"u113"},
    "15b546440b3b47bd8cf922019b56b597":{
      "scriptId":"u114"},
    "784ea6c7ffa743c1b2443e55b27183a3":{
      "scriptId":"u115"}}});