$axure.loadCurrentPage({
  "url":"违规客户权限注销.html",
  "generationDate":new Date(1413021325849.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"193f4bc470064768bfa0e963eab1ead0",
    "type":"Axure:Page",
    "name":"违规客户权限注销",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c1666168c94e3baf1d3bfe07423490",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":970,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff627f7127eb4afb87ab2df30c85a1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":970,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/店铺信息/u0.png"}},
{
          "id":"b46407a373914665b508a311f364fb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":0,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8abc925174c41dd8fd6f814e411cff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":0,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"0252a9a268be4ef2818280d0717b9ce9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":100,
              "y":67},
            "size":{
              "width":768,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a4cecc964043958d90ac80512dff73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":100,
                  "y":67},
                "size":{
                  "width":768,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u4.png"}},
{
          "id":"f511c452d4a14dffbe4c0847eddf625d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":868,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e3c5790d0b42c0b001030fb1957b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":868,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"89525d7147e54c5dbc646879351c7966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":608},
            "size":{
              "width":970,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2003e953eaab478b9d8d70ab743a5247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":608},
                "size":{
                  "width":970,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u36.png"}},
{
          "id":"aad78a3a8e8741a2939eafbd5b257208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":970,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1154c207ed6a488f9598b2fdb9b72373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":617},
                "size":{
                  "width":970,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u38.png"}},
{
          "id":"3f7f4fb5082e4988811fc8b4a23851c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c88e13368e84bbcbed34b0efc9ddd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c7304ef9d684a2d90cc3f056fa5248c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae9760916f9424c9917598b067074c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed860859a0a24b1e8f1161c8d549cc71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":444,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86996885e3445d58c07b06256ea0921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":444,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca4e3badb92405b8f60f4698388bce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":600,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc5b73c08db441da45be3fdff6e5471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":600,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2cb1543b524828987bf2d62d9e9caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":180,
              "y":670},
            "size":{
              "width":730,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c8fce9811948daa0f207789af7475e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":670},
                "size":{
                  "width":730,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c998ed93cbb64e23a970f3ea6ea88915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":105},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f37dd473e0449538fb2674829e2b35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":105},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cacdd89a528344dfa8058ef91bd846d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":130},
            "size":{
              "width":92,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3ec3da4c834fc4adba428959365fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":130},
                "size":{
                  "width":92,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5daf66c73ff4b5b88fb4161a1b6009d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":153},
            "size":{
              "width":80,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffb3eb8450d4d33b53b35c5f5425974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":153},
                "size":{
                  "width":80,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b57edcd60cdb45808ac39c133eef85de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":177},
            "size":{
              "width":92,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c3bc78b6284cbd806cc9f40debb658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":177},
                "size":{
                  "width":92,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"988bbc16994f43a5a9801c799d12121d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":197},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3db4d053277d4950adc7ecca54e454b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":197},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0742472d40b43a78616f2972fe10445",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":297},
            "size":{
              "width":100,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58ee195d49a4fe1affb4c99fbe76cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":297},
                "size":{
                  "width":100,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55670c3c879e402b9defb2f9718d7b3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":222},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f882ca2105544b79f4614407b048b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":222},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8cd8faf6724455997eeaf176f45bee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":141,
              "y":314},
            "size":{
              "width":109,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36eabcf220854d078eac8bccdbf4ffe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":314},
                "size":{
                  "width":109,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2bdd0e68cca4621b7ae206ae042202a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":242},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe427b26eeac47bbbd72f011660c1976",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":242},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1722d4c0f65a4fc0a1b5b3948423d4ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":260},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3792dd5ab13342eba4c8a29e9a29e4e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":260},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"254117c7fc7a4aebb8314d964a7f25fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":280},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcb13886834a47e5b87d41f9b1d02371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":280},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d26e4b3503d642119566feb5740b6e98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":278,
              "y":101},
            "size":{
              "width":124,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93edcd8f46ab472bbdb03e0a867244ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":278,
                  "y":101},
                "size":{
                  "width":124,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d49c4974de0a4fe7978d862a82e7076e",
          "label":"Date Field From",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":435,
              "y":99},
            "size":{
              "width":146,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"921ffc04b68f4c9abd6efab77a720a99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC00},
            "location":{
              "x":714,
              "y":92},
            "size":{
              "width":91,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa8f3bf7259c4b7192adddb118ba1138",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00},
                "location":{
                  "x":714,
                  "y":92},
                "size":{
                  "width":91,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/违规客户权限注销/u47.png"}},
{
          "id":"875b3ef120d74adf9eb621dd53d3e659",
          "label":"tab1",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":167},
            "size":{
              "width":590,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ff057d94b2b4c89af442d2e16c261e9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":64,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fd8af4760ec542a6bfe84733c40eaa4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":64,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u64.png"}},
{
              "id":"f55c5e4e375b4ef3af3ddc18f05fb481",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":62},
                "size":{
                  "width":64,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b5a5b2b96504264bf93ef63a7406f47",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":62},
                    "size":{
                      "width":64,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/退款审核_1/u89.png"}},
{
              "id":"1e5e63fda35b44848420e30f8f0fdead",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":64,
                  "y":36},
                "size":{
                  "width":66,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0d8195db8fb64699b90a25b1ca8c0d4f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":64,
                      "y":36},
                    "size":{
                      "width":66,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u51.png"}},
{
              "id":"2218dfa6520f4f3895b8309415a16905",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":64,
                  "y":62},
                "size":{
                  "width":66,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d65e611625e444a689fcb6edb461c90e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":64,
                      "y":62},
                    "size":{
                      "width":66,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u59.png"}},
{
              "id":"1fd4fad959904517806fcb5c0e3b02f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":64,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f642addf4eba458983adbbb13fd852d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":64,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/退款审核_1/u129.png"}},
{
              "id":"66d0007f2fe34963b41ee4239a6f453e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":64,
                  "y":90},
                "size":{
                  "width":66,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8845814e695430e862fea0967f85c01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":64,
                      "y":90},
                    "size":{
                      "width":66,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/评价类别配置/u128.png"}},
{
              "id":"1a7ed22ef3654e76b6a42fb7c45e70a4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":520,
                  "y":36},
                "size":{
                  "width":70,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"100d59747ca2410ab95cb71e245f3f78",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF23BEB1,
                      "opacity":1},
                    "location":{
                      "x":520,
                      "y":36},
                    "size":{
                      "width":70,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u76.png"}},
{
              "id":"a618bf1cb32d490aaaa3e78f35a3f522",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":520,
                  "y":62},
                "size":{
                  "width":70,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cbf34199e3324b53b64e8f23ca900593",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF23BEB1,
                      "opacity":1},
                    "location":{
                      "x":520,
                      "y":62},
                    "size":{
                      "width":70,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u90.png"}},
{
              "id":"dd1ad5984ded4dee8c47b08e59583718",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":520,
                  "y":90},
                "size":{
                  "width":70,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05c604675be546ad9601ca5122d5ff5a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF23BEB1,
                      "opacity":1},
                    "location":{
                      "x":520,
                      "y":90},
                    "size":{
                      "width":70,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u104.png"}},
{
              "id":"2970f8ff148744ecada1dc8c0a992f94",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":64,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ae2509fa0a7479d8bd9b19a923139fe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":64,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/退款审核_1/u49.png"}},
{
              "id":"bdd66512cd354e1ca813c015ef879952",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":64,
                  "y":0},
                "size":{
                  "width":66,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cfe8b7bd51864dd68226a69ef6906b01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":64,
                      "y":0},
                    "size":{
                      "width":66,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u43.png"}},
{
              "id":"3f84e0e2856d4080a9a3102abef688e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":520,
                  "y":0},
                "size":{
                  "width":70,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8590bb91241c4c9c82497194efb23922",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":520,
                      "y":0},
                    "size":{
                      "width":70,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u62.png"}},
{
              "id":"77ea0884ad9046fcab270f4a73a79998",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":130,
                  "y":0},
                "size":{
                  "width":63,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f64784cd0c0e4aa5a708fd5af4e19365",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":130,
                      "y":0},
                    "size":{
                      "width":63,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u54.png"}},
{
              "id":"9c413576445b4cd38689371e4ef9e1d5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":36},
                "size":{
                  "width":63,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f89f39952d024e4a96c70962d3034f61",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":130,
                      "y":36},
                    "size":{
                      "width":63,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u68.png"}},
{
              "id":"74fb8a53bc3241bb9c18b5c09a53bc13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":62},
                "size":{
                  "width":63,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90098a82a3f848f59dac3db6106f9dd0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":130,
                      "y":62},
                    "size":{
                      "width":63,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u82.png"}},
{
              "id":"12224665d7b0430ea45e1e58d7f38be5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":90},
                "size":{
                  "width":63,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b88a5a34beb54202b50e95ad17bebd64",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":130,
                      "y":90},
                    "size":{
                      "width":63,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u96.png"}},
{
              "id":"b073fac20c8042d6b641e8cc0ca8a1c4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":436,
                  "y":0},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02fb89d888ae40d7b378b552f2bffeaf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":436,
                      "y":0},
                    "size":{
                      "width":84,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u45.png"}},
{
              "id":"d4bc4ac6c73a424c9d48a941e8603b62",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":36},
                "size":{
                  "width":84,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f4cac8909f0a4f54a27f31a2488e4df1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":436,
                      "y":36},
                    "size":{
                      "width":84,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u53.png"}},
{
              "id":"a5d68349d93d4e988de6c1f6fd14bef8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":62},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d767ac0342d041c6860b458c7b7834e8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":436,
                      "y":62},
                    "size":{
                      "width":84,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u61.png"}},
{
              "id":"d5ad3a7cd0e74c82ae674a60a1a8d63b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":90},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"48cf72757a814586bb323d600976fdb2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":436,
                      "y":90},
                    "size":{
                      "width":84,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u100.png"}},
{
              "id":"2f9ac1265ac14c698ec16b5e0fc49062",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":352,
                  "y":0},
                "size":{
                  "width":84,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5ea690d223db4122a884ca0b0e78a940",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":352,
                      "y":0},
                    "size":{
                      "width":84,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u45.png"}},
{
              "id":"61e81a79e88247e292c029f1cde0a1e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":352,
                  "y":36},
                "size":{
                  "width":84,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eed44c72ca284dfcb6abd30e4d39930d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":352,
                      "y":36},
                    "size":{
                      "width":84,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u53.png"}},
{
              "id":"ffad21529f044a8f90a5816e407b2144",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":352,
                  "y":62},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03b89cdde95140fbbc1dc688bc903384",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":352,
                      "y":62},
                    "size":{
                      "width":84,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理/u61.png"}},
{
              "id":"94b12ebfc29f4f7ca2f5ab33b4251da1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":352,
                  "y":90},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d4214d599cf493980ff3c8d65614cf7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":352,
                      "y":90},
                    "size":{
                      "width":84,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u100.png"}},
{
              "id":"3580af9cae1b4e1cbb5a60c2dd3ce7e9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":193,
                  "y":0},
                "size":{
                  "width":159,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dcc59d7bb14431b9a8810ed3911e44f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":193,
                      "y":0},
                    "size":{
                      "width":159,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u56.png"}},
{
              "id":"09b0bf15747c4cf7b2eb97796c180bfa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":36},
                "size":{
                  "width":159,
                  "height":26}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ad5ce37d4a948058789ccd72298bb8c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":193,
                      "y":36},
                    "size":{
                      "width":159,
                      "height":26}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u70.png"}},
{
              "id":"370f31aa474e4c3ab43e35d27bada01f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":62},
                "size":{
                  "width":159,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e88ece68c7df44e39a46a860749ea948",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":193,
                      "y":62},
                    "size":{
                      "width":159,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u84.png"}},
{
              "id":"543701839e2640489d07d3cdc3635f03",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":90},
                "size":{
                  "width":159,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a2c26dceb18478c8608b3fc8ac20f76",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":193,
                      "y":90},
                    "size":{
                      "width":159,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/违规客户权限注销/u98.png"}}]},
{
          "id":"4fa395b41a3940b89ca9eaedcf12f873",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":153},
            "size":{
              "width":564,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF23BEB1}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/财务数据/u54_line.png"}},
{
          "id":"f4bba8a4d0984215a8d9b8d071c5e9ab",
          "label":"b1",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":278,
              "y":134},
            "size":{
              "width":124,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6f6e77339d6483a9e3f073669608eb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":278,
                  "y":134},
                "size":{
                  "width":124,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工单登记/b1_u133.png",
            "selected~":"images/工单登记/b1_u133_selected.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "03c1666168c94e3baf1d3bfe07423490":{
      "scriptId":"u0"},
    "ff627f7127eb4afb87ab2df30c85a1bd":{
      "scriptId":"u1"},
    "b46407a373914665b508a311f364fb8d":{
      "scriptId":"u2"},
    "d8abc925174c41dd8fd6f814e411cff5":{
      "scriptId":"u3"},
    "0252a9a268be4ef2818280d0717b9ce9":{
      "scriptId":"u4"},
    "e1a4cecc964043958d90ac80512dff73":{
      "scriptId":"u5"},
    "f511c452d4a14dffbe4c0847eddf625d":{
      "scriptId":"u6"},
    "e4e3c5790d0b42c0b001030fb1957b71":{
      "scriptId":"u7"},
    "89525d7147e54c5dbc646879351c7966":{
      "scriptId":"u8"},
    "2003e953eaab478b9d8d70ab743a5247":{
      "scriptId":"u9"},
    "aad78a3a8e8741a2939eafbd5b257208":{
      "scriptId":"u10"},
    "1154c207ed6a488f9598b2fdb9b72373":{
      "scriptId":"u11"},
    "3f7f4fb5082e4988811fc8b4a23851c4":{
      "scriptId":"u12"},
    "1c88e13368e84bbcbed34b0efc9ddd49":{
      "scriptId":"u13"},
    "1c7304ef9d684a2d90cc3f056fa5248c":{
      "scriptId":"u14"},
    "eae9760916f9424c9917598b067074c6":{
      "scriptId":"u15"},
    "ed860859a0a24b1e8f1161c8d549cc71":{
      "scriptId":"u16"},
    "b86996885e3445d58c07b06256ea0921":{
      "scriptId":"u17"},
    "8ca4e3badb92405b8f60f4698388bce7":{
      "scriptId":"u18"},
    "4bc5b73c08db441da45be3fdff6e5471":{
      "scriptId":"u19"},
    "4d2cb1543b524828987bf2d62d9e9caf":{
      "scriptId":"u20"},
    "e9c8fce9811948daa0f207789af7475e":{
      "scriptId":"u21"},
    "c998ed93cbb64e23a970f3ea6ea88915":{
      "scriptId":"u22"},
    "3f37dd473e0449538fb2674829e2b35f":{
      "scriptId":"u23"},
    "cacdd89a528344dfa8058ef91bd846d1":{
      "scriptId":"u24"},
    "7c3ec3da4c834fc4adba428959365fbb":{
      "scriptId":"u25"},
    "d5daf66c73ff4b5b88fb4161a1b6009d":{
      "scriptId":"u26"},
    "8ffb3eb8450d4d33b53b35c5f5425974":{
      "scriptId":"u27"},
    "b57edcd60cdb45808ac39c133eef85de":{
      "scriptId":"u28"},
    "43c3bc78b6284cbd806cc9f40debb658":{
      "scriptId":"u29"},
    "988bbc16994f43a5a9801c799d12121d":{
      "scriptId":"u30"},
    "3db4d053277d4950adc7ecca54e454b0":{
      "scriptId":"u31"},
    "c0742472d40b43a78616f2972fe10445":{
      "scriptId":"u32"},
    "d58ee195d49a4fe1affb4c99fbe76cf0":{
      "scriptId":"u33"},
    "55670c3c879e402b9defb2f9718d7b3c":{
      "scriptId":"u34"},
    "7f882ca2105544b79f4614407b048b05":{
      "scriptId":"u35"},
    "c8cd8faf6724455997eeaf176f45bee3":{
      "scriptId":"u36"},
    "36eabcf220854d078eac8bccdbf4ffe7":{
      "scriptId":"u37"},
    "c2bdd0e68cca4621b7ae206ae042202a":{
      "scriptId":"u38"},
    "fe427b26eeac47bbbd72f011660c1976":{
      "scriptId":"u39"},
    "1722d4c0f65a4fc0a1b5b3948423d4ef":{
      "scriptId":"u40"},
    "3792dd5ab13342eba4c8a29e9a29e4e0":{
      "scriptId":"u41"},
    "254117c7fc7a4aebb8314d964a7f25fa":{
      "scriptId":"u42"},
    "bcb13886834a47e5b87d41f9b1d02371":{
      "scriptId":"u43"},
    "d26e4b3503d642119566feb5740b6e98":{
      "scriptId":"u44"},
    "93edcd8f46ab472bbdb03e0a867244ec":{
      "scriptId":"u45"},
    "d49c4974de0a4fe7978d862a82e7076e":{
      "scriptId":"u46"},
    "921ffc04b68f4c9abd6efab77a720a99":{
      "scriptId":"u47"},
    "fa8f3bf7259c4b7192adddb118ba1138":{
      "scriptId":"u48"},
    "875b3ef120d74adf9eb621dd53d3e659":{
      "scriptId":"u49"},
    "2970f8ff148744ecada1dc8c0a992f94":{
      "scriptId":"u50"},
    "8ae2509fa0a7479d8bd9b19a923139fe":{
      "scriptId":"u51"},
    "bdd66512cd354e1ca813c015ef879952":{
      "scriptId":"u52"},
    "cfe8b7bd51864dd68226a69ef6906b01":{
      "scriptId":"u53"},
    "77ea0884ad9046fcab270f4a73a79998":{
      "scriptId":"u54"},
    "f64784cd0c0e4aa5a708fd5af4e19365":{
      "scriptId":"u55"},
    "3580af9cae1b4e1cbb5a60c2dd3ce7e9":{
      "scriptId":"u56"},
    "5dcc59d7bb14431b9a8810ed3911e44f":{
      "scriptId":"u57"},
    "2f9ac1265ac14c698ec16b5e0fc49062":{
      "scriptId":"u58"},
    "5ea690d223db4122a884ca0b0e78a940":{
      "scriptId":"u59"},
    "b073fac20c8042d6b641e8cc0ca8a1c4":{
      "scriptId":"u60"},
    "02fb89d888ae40d7b378b552f2bffeaf":{
      "scriptId":"u61"},
    "3f84e0e2856d4080a9a3102abef688e1":{
      "scriptId":"u62"},
    "8590bb91241c4c9c82497194efb23922":{
      "scriptId":"u63"},
    "6ff057d94b2b4c89af442d2e16c261e9":{
      "scriptId":"u64"},
    "fd8af4760ec542a6bfe84733c40eaa4b":{
      "scriptId":"u65"},
    "1e5e63fda35b44848420e30f8f0fdead":{
      "scriptId":"u66"},
    "0d8195db8fb64699b90a25b1ca8c0d4f":{
      "scriptId":"u67"},
    "9c413576445b4cd38689371e4ef9e1d5":{
      "scriptId":"u68"},
    "f89f39952d024e4a96c70962d3034f61":{
      "scriptId":"u69"},
    "09b0bf15747c4cf7b2eb97796c180bfa":{
      "scriptId":"u70"},
    "6ad5ce37d4a948058789ccd72298bb8c":{
      "scriptId":"u71"},
    "61e81a79e88247e292c029f1cde0a1e3":{
      "scriptId":"u72"},
    "eed44c72ca284dfcb6abd30e4d39930d":{
      "scriptId":"u73"},
    "d4bc4ac6c73a424c9d48a941e8603b62":{
      "scriptId":"u74"},
    "f4cac8909f0a4f54a27f31a2488e4df1":{
      "scriptId":"u75"},
    "1a7ed22ef3654e76b6a42fb7c45e70a4":{
      "scriptId":"u76"},
    "100d59747ca2410ab95cb71e245f3f78":{
      "scriptId":"u77"},
    "f55c5e4e375b4ef3af3ddc18f05fb481":{
      "scriptId":"u78"},
    "3b5a5b2b96504264bf93ef63a7406f47":{
      "scriptId":"u79"},
    "2218dfa6520f4f3895b8309415a16905":{
      "scriptId":"u80"},
    "d65e611625e444a689fcb6edb461c90e":{
      "scriptId":"u81"},
    "74fb8a53bc3241bb9c18b5c09a53bc13":{
      "scriptId":"u82"},
    "90098a82a3f848f59dac3db6106f9dd0":{
      "scriptId":"u83"},
    "370f31aa474e4c3ab43e35d27bada01f":{
      "scriptId":"u84"},
    "e88ece68c7df44e39a46a860749ea948":{
      "scriptId":"u85"},
    "ffad21529f044a8f90a5816e407b2144":{
      "scriptId":"u86"},
    "03b89cdde95140fbbc1dc688bc903384":{
      "scriptId":"u87"},
    "a5d68349d93d4e988de6c1f6fd14bef8":{
      "scriptId":"u88"},
    "d767ac0342d041c6860b458c7b7834e8":{
      "scriptId":"u89"},
    "a618bf1cb32d490aaaa3e78f35a3f522":{
      "scriptId":"u90"},
    "cbf34199e3324b53b64e8f23ca900593":{
      "scriptId":"u91"},
    "1fd4fad959904517806fcb5c0e3b02f1":{
      "scriptId":"u92"},
    "f642addf4eba458983adbbb13fd852d5":{
      "scriptId":"u93"},
    "66d0007f2fe34963b41ee4239a6f453e":{
      "scriptId":"u94"},
    "f8845814e695430e862fea0967f85c01":{
      "scriptId":"u95"},
    "12224665d7b0430ea45e1e58d7f38be5":{
      "scriptId":"u96"},
    "b88a5a34beb54202b50e95ad17bebd64":{
      "scriptId":"u97"},
    "543701839e2640489d07d3cdc3635f03":{
      "scriptId":"u98"},
    "8a2c26dceb18478c8608b3fc8ac20f76":{
      "scriptId":"u99"},
    "94b12ebfc29f4f7ca2f5ab33b4251da1":{
      "scriptId":"u100"},
    "9d4214d599cf493980ff3c8d65614cf7":{
      "scriptId":"u101"},
    "d5ad3a7cd0e74c82ae674a60a1a8d63b":{
      "scriptId":"u102"},
    "48cf72757a814586bb323d600976fdb2":{
      "scriptId":"u103"},
    "dd1ad5984ded4dee8c47b08e59583718":{
      "scriptId":"u104"},
    "05c604675be546ad9601ca5122d5ff5a":{
      "scriptId":"u105"},
    "4fa395b41a3940b89ca9eaedcf12f873":{
      "scriptId":"u106"},
    "f4bba8a4d0984215a8d9b8d071c5e9ab":{
      "scriptId":"u107"},
    "f6f6e77339d6483a9e3f073669608eb5":{
      "scriptId":"u108"}}});