$axure.loadCurrentPage({
  "url":"申请合作.html",
  "generationDate":new Date(1413021310578.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6cb52f83595c403d8b9c0d5686df2b3f",
    "type":"Axure:Page",
    "name":"申请合作",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6cecda4089c6481d941fd18539533cae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":1,
              "y":68},
            "size":{
              "width":100,
              "height":1612},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b31f82e206a4930b20c4d6372cbef9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":1,
                  "y":68},
                "size":{
                  "width":100,
                  "height":1612},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u0.png"}},
{
          "id":"a8364ab083aa484cb8054942735f00b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":101,
              "y":68},
            "size":{
              "width":539,
              "height":1612},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0b71f78ae1341ef811914795ad1e405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":101,
                  "y":68},
                "size":{
                  "width":539,
                  "height":1612},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u2.png"}},
{
          "id":"d2d7bfee38a84b2fb9e860f8509641f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":869,
              "y":67},
            "size":{
              "width":100,
              "height":1612},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6894ddf8e94b4f8ebd29f60d672a4276",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":869,
                  "y":67},
                "size":{
                  "width":100,
                  "height":1612},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u0.png"}},
{
          "id":"f8708402e9354f6b82a90a1c3a06044c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":640,
              "y":68},
            "size":{
              "width":20,
              "height":1612},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa98064ff9ed4b9cb537a7052b2f86c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":640,
                  "y":68},
                "size":{
                  "width":20,
                  "height":1612},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u6.png"}},
{
          "id":"064a90c0bcc04216860a73fdc08f4406",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":660,
              "y":68},
            "size":{
              "width":210,
              "height":1612},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dd0df3b50a34a1da213f6fd275e92f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":660,
                  "y":68},
                "size":{
                  "width":210,
                  "height":1612},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u8.png"}},
{
          "id":"9bf650cebb664158bdecd45a8ef50650",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":970,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5ed02ffb3dd444caaa94b82382962c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":970,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u10.png"}},
{
          "id":"5f4bdfa0240d405f9236b94edff59058",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":101,
              "y":69},
            "size":{
              "width":539,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdcf81f3dff74103ac4574ff0dbf5cc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":101,
                  "y":69},
                "size":{
                  "width":539,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u12.png"}},
{
          "id":"9e2e989b59bf46109e190022e69b227b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":107},
            "size":{
              "width":428,
              "height":261}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ed115d7b5564dc2a472b5e326d99059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":107},
                "size":{
                  "width":428,
                  "height":261}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u14.png"}},
{
          "id":"cd1034c6f3f94f9ea474cecb7af665d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":368},
            "size":{
              "width":514,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e03be58d5f2a45a988c3e2d5a9b4ffae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":368},
                "size":{
                  "width":514,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u16.png"}},
{
          "id":"db3d23b475c04a4c9b8d8adc86b9da0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":438},
            "size":{
              "width":529,
              "height":142}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50a5704708974d008f1d55ca419b2d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":438},
                "size":{
                  "width":529,
                  "height":142}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u18.png"}},
{
          "id":"56d3033698684099968c91dc13962b2b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":570},
            "size":{
              "width":471,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d79b18da18144dc8efa89fbe4193955",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":570},
                "size":{
                  "width":471,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u20.png"}},
{
          "id":"b1e4795eb43648708491fa42a4fdf861",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":688},
            "size":{
              "width":409,
              "height":354}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f263e91a57e14ca099f6c35e72512384",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":688},
                "size":{
                  "width":409,
                  "height":354}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u22.png"}},
{
          "id":"a1d7aed3da6c42a88c99e01048ad114f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":1042},
            "size":{
              "width":520,
              "height":173}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf1d9b4ab08742518414f6094f89b148",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":1042},
                "size":{
                  "width":520,
                  "height":173}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u24.png"}},
{
          "id":"1f1ed10dbc6345ee8e874f9c0afe6af0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":1215},
            "size":{
              "width":304,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4854cafcb54d969ea90ff1b29bacb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":109,
                  "y":1215},
                "size":{
                  "width":304,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u26.png"}},
{
          "id":"53cf3fc730c84c35a3c6c6288d106c80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":1253},
            "size":{
              "width":451,
              "height":313}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9a0c819630d428e95d8ad0fe8c60447",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":102,
                  "y":1253},
                "size":{
                  "width":451,
                  "height":313}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u28.png"}},
{
          "id":"9999fdfcf85e4e5a90bb51f1d0f5190b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255.5,
              "y":1585},
            "size":{
              "width":196,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec1d3a3c9972479ca1688d2530212084",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255.5,
                  "y":1585},
                "size":{
                  "width":196,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u30.png"}},
{
          "id":"09e19c49c5e746e69dbada601f2be8e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":75},
            "size":{
              "width":213,
              "height":376}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c763ae5bb7044855a9c6560a337eb554",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":75},
                "size":{
                  "width":213,
                  "height":376}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u32.png"}},
{
          "id":"7e0e55f6b1b547b7ae6108a801106daa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":461},
            "size":{
              "width":216,
              "height":396}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d9f93d0d64c487683cdb78a2124065e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":461},
                "size":{
                  "width":216,
                  "height":396}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u34.png"}},
{
          "id":"a23cfaa0ea834c25bde55e5af56dbbfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":1678},
            "size":{
              "width":970,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84aededd297641e9b4cd90399c223bc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":1678},
                "size":{
                  "width":970,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u36.png"}},
{
          "id":"8b5c0803908444fbbcc0f26f8db73728",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":1687},
            "size":{
              "width":970,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b36c1fc3c39e432185d1e566ae6c266b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":1687},
                "size":{
                  "width":970,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u38.png"}},
{
          "id":"a08833f50ee84949ac27e1c5c0ec60ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":1699},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724e19f2c6af49a285181657022cd1df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":1699},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b8434fa82944ceca5c08fc8f1331466",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":1699},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87fc9b3f6b8747acb8696c4f496f0ad2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":1699},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"246287aa82b242cd902a81f58a73cd4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":444,
              "y":1699},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0492c9f1845c4b2b972359a6d89aa7ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":444,
                  "y":1699},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0ec4794ddc64b92bf5c040f6830bb5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":600,
              "y":1699},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f201a340f79047928d6a4142906e7441",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":600,
                  "y":1699},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd665722bab9433b87e56719646fcde8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":180,
              "y":1740},
            "size":{
              "width":730,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dedfb62fe7614db8b41396e3600757fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":1740},
                "size":{
                  "width":730,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6cecda4089c6481d941fd18539533cae":{
      "scriptId":"u0"},
    "1b31f82e206a4930b20c4d6372cbef9a":{
      "scriptId":"u1"},
    "a8364ab083aa484cb8054942735f00b9":{
      "scriptId":"u2"},
    "d0b71f78ae1341ef811914795ad1e405":{
      "scriptId":"u3"},
    "d2d7bfee38a84b2fb9e860f8509641f7":{
      "scriptId":"u4"},
    "6894ddf8e94b4f8ebd29f60d672a4276":{
      "scriptId":"u5"},
    "f8708402e9354f6b82a90a1c3a06044c":{
      "scriptId":"u6"},
    "fa98064ff9ed4b9cb537a7052b2f86c1":{
      "scriptId":"u7"},
    "064a90c0bcc04216860a73fdc08f4406":{
      "scriptId":"u8"},
    "1dd0df3b50a34a1da213f6fd275e92f2":{
      "scriptId":"u9"},
    "9bf650cebb664158bdecd45a8ef50650":{
      "scriptId":"u10"},
    "c5ed02ffb3dd444caaa94b82382962c8":{
      "scriptId":"u11"},
    "5f4bdfa0240d405f9236b94edff59058":{
      "scriptId":"u12"},
    "cdcf81f3dff74103ac4574ff0dbf5cc5":{
      "scriptId":"u13"},
    "9e2e989b59bf46109e190022e69b227b":{
      "scriptId":"u14"},
    "6ed115d7b5564dc2a472b5e326d99059":{
      "scriptId":"u15"},
    "cd1034c6f3f94f9ea474cecb7af665d4":{
      "scriptId":"u16"},
    "e03be58d5f2a45a988c3e2d5a9b4ffae":{
      "scriptId":"u17"},
    "db3d23b475c04a4c9b8d8adc86b9da0f":{
      "scriptId":"u18"},
    "50a5704708974d008f1d55ca419b2d96":{
      "scriptId":"u19"},
    "56d3033698684099968c91dc13962b2b":{
      "scriptId":"u20"},
    "7d79b18da18144dc8efa89fbe4193955":{
      "scriptId":"u21"},
    "b1e4795eb43648708491fa42a4fdf861":{
      "scriptId":"u22"},
    "f263e91a57e14ca099f6c35e72512384":{
      "scriptId":"u23"},
    "a1d7aed3da6c42a88c99e01048ad114f":{
      "scriptId":"u24"},
    "cf1d9b4ab08742518414f6094f89b148":{
      "scriptId":"u25"},
    "1f1ed10dbc6345ee8e874f9c0afe6af0":{
      "scriptId":"u26"},
    "1a4854cafcb54d969ea90ff1b29bacb7":{
      "scriptId":"u27"},
    "53cf3fc730c84c35a3c6c6288d106c80":{
      "scriptId":"u28"},
    "c9a0c819630d428e95d8ad0fe8c60447":{
      "scriptId":"u29"},
    "9999fdfcf85e4e5a90bb51f1d0f5190b":{
      "scriptId":"u30"},
    "ec1d3a3c9972479ca1688d2530212084":{
      "scriptId":"u31"},
    "09e19c49c5e746e69dbada601f2be8e1":{
      "scriptId":"u32"},
    "c763ae5bb7044855a9c6560a337eb554":{
      "scriptId":"u33"},
    "7e0e55f6b1b547b7ae6108a801106daa":{
      "scriptId":"u34"},
    "8d9f93d0d64c487683cdb78a2124065e":{
      "scriptId":"u35"},
    "a23cfaa0ea834c25bde55e5af56dbbfa":{
      "scriptId":"u36"},
    "84aededd297641e9b4cd90399c223bc7":{
      "scriptId":"u37"},
    "8b5c0803908444fbbcc0f26f8db73728":{
      "scriptId":"u38"},
    "b36c1fc3c39e432185d1e566ae6c266b":{
      "scriptId":"u39"},
    "a08833f50ee84949ac27e1c5c0ec60ca":{
      "scriptId":"u40"},
    "724e19f2c6af49a285181657022cd1df":{
      "scriptId":"u41"},
    "9b8434fa82944ceca5c08fc8f1331466":{
      "scriptId":"u42"},
    "87fc9b3f6b8747acb8696c4f496f0ad2":{
      "scriptId":"u43"},
    "246287aa82b242cd902a81f58a73cd4d":{
      "scriptId":"u44"},
    "0492c9f1845c4b2b972359a6d89aa7ea":{
      "scriptId":"u45"},
    "a0ec4794ddc64b92bf5c040f6830bb5b":{
      "scriptId":"u46"},
    "f201a340f79047928d6a4142906e7441":{
      "scriptId":"u47"},
    "dd665722bab9433b87e56719646fcde8":{
      "scriptId":"u48"},
    "dedfb62fe7614db8b41396e3600757fb":{
      "scriptId":"u49"}}});