$axure.loadCurrentPage({
  "url":"门店评价排名.html",
  "generationDate":new Date(1413021311497.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"65458b715b9f487cacb486f58dd15ddd",
    "type":"Axure:Page",
    "name":"门店评价排名",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c1666168c94e3baf1d3bfe07423490",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":970,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff627f7127eb4afb87ab2df30c85a1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":970,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u10.png"}},
{
          "id":"b46407a373914665b508a311f364fb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":0,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8abc925174c41dd8fd6f814e411cff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":0,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"0252a9a268be4ef2818280d0717b9ce9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":100,
              "y":67},
            "size":{
              "width":768,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a4cecc964043958d90ac80512dff73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":100,
                  "y":67},
                "size":{
                  "width":768,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u4.png"}},
{
          "id":"f511c452d4a14dffbe4c0847eddf625d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":868,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e3c5790d0b42c0b001030fb1957b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":868,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"89525d7147e54c5dbc646879351c7966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":608},
            "size":{
              "width":970,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2003e953eaab478b9d8d70ab743a5247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":608},
                "size":{
                  "width":970,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u36.png"}},
{
          "id":"aad78a3a8e8741a2939eafbd5b257208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":970,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1154c207ed6a488f9598b2fdb9b72373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":617},
                "size":{
                  "width":970,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u38.png"}},
{
          "id":"3f7f4fb5082e4988811fc8b4a23851c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c88e13368e84bbcbed34b0efc9ddd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c7304ef9d684a2d90cc3f056fa5248c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae9760916f9424c9917598b067074c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed860859a0a24b1e8f1161c8d549cc71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":444,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86996885e3445d58c07b06256ea0921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":444,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca4e3badb92405b8f60f4698388bce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":600,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc5b73c08db441da45be3fdff6e5471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":600,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2cb1543b524828987bf2d62d9e9caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":180,
              "y":670},
            "size":{
              "width":730,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c8fce9811948daa0f207789af7475e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":670},
                "size":{
                  "width":730,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c998ed93cbb64e23a970f3ea6ea88915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":105},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f37dd473e0449538fb2674829e2b35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":105},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cacdd89a528344dfa8058ef91bd846d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":130},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3ec3da4c834fc4adba428959365fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":130},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5daf66c73ff4b5b88fb4161a1b6009d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":156},
            "size":{
              "width":80,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffb3eb8450d4d33b53b35c5f5425974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":156},
                "size":{
                  "width":80,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f2060315414ec8943fe2e6b11dbc0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":181},
            "size":{
              "width":90,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d27c5e6343d0416f9a1ff24c5cd07755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":181},
                "size":{
                  "width":90,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b57edcd60cdb45808ac39c133eef85de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":205},
            "size":{
              "width":92,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c3bc78b6284cbd806cc9f40debb658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":205},
                "size":{
                  "width":92,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89b019dab1b04cadb3b9a519186fc70b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":231},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff2fccf858348e0892846d382b4a22b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":231},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd8eeff987774ec79e928768ccbd9cb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":255},
            "size":{
              "width":91,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"434de672b0bf44639eabacde8cfd3ab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":255},
                "size":{
                  "width":91,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2df02b8672f4ac39112063cb8770d13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":279},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d89ee1e4aaf748deba51d948bd82a93b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":279},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c186dca97f4419a8dc82135c8a06c87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":347},
            "size":{
              "width":100,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d08114d29f43ef9c8270c8391d9375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":347},
                "size":{
                  "width":100,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"988bbc16994f43a5a9801c799d12121d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":373},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3db4d053277d4950adc7ecca54e454b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":373},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0742472d40b43a78616f2972fe10445",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":398},
            "size":{
              "width":100,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58ee195d49a4fe1affb4c99fbe76cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":398},
                "size":{
                  "width":100,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6f1226af4ea44e48806b7d30249acaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":141,
              "y":302},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ce440aeb924762b6bb943b6514a486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":302},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26a57ef67c81421f98f42f4580afd175",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":141,
              "y":324},
            "size":{
              "width":89,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58873b1d017c4ee4b8c8b0743853fa92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":324},
                "size":{
                  "width":89,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26eece99fd6d43aca84a3fa6260624e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":262,
              "y":89},
            "size":{
              "width":145,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa4020c55d64d4dac57f75ec1363af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":262,
                  "y":89},
                "size":{
                  "width":145,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d6331d077654cc2abc6667d7f49a02f",
          "label":"tab1",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":254.5,
              "y":130},
            "size":{
              "width":581,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a95354d77194a5599a0ca22364a313b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d44b40c525a4470c805a70bfc37477bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u51.png"}},
{
              "id":"30ac0854d4514da0b82c21eac98e2bd6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"52ae2c441d9f41a3947619d3a698a3ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u61.png"}},
{
              "id":"166d808614b5456d9e633b60979a3583",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":126,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e7fd831086c416caed7412f4b597534",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":126,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u71.png"}},
{
              "id":"22e1d491804f43f998b36efa67c81d81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":126,
                  "y":0},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b956d71e78c14ebf8e4070f06dad00c9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":126,
                      "y":0},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u51.png"}},
{
              "id":"563bbc21a1294c8f8259dcaafbdd56f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":30},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e173628104774876b3dc08361d99ed56",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u61.png"}},
{
              "id":"e61832b47e1c4cdf979b4aa587ecb8af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":60},
                "size":{
                  "width":126,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bf82f1cf05dd4748aaca42b845011c88",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":60},
                    "size":{
                      "width":126,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u71.png"}},
{
              "id":"9959d1614263411e8fae66c1a2a8958f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":252,
                  "y":0},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe591c40b5d6407e97ac166907eeb652",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":252,
                      "y":0},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u51.png"}},
{
              "id":"edd0211e84b84165ae5db69868f562e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":252,
                  "y":30},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a6125e5304e8493c96549fe4b719179e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":252,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u61.png"}},
{
              "id":"7a51dd96c67a4326b65637aa45f259cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":252,
                  "y":60},
                "size":{
                  "width":126,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fc884954d51a4eb2b539fa3fa44299e1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":252,
                      "y":60},
                    "size":{
                      "width":126,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u71.png"}},
{
              "id":"2d087a5c22a247a59909b73e699981ca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":494,
                  "y":0},
                "size":{
                  "width":87,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8a28c2a84964042a72b2270374fd8b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":494,
                      "y":0},
                    "size":{
                      "width":87,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u59.png"}},
{
              "id":"9993c352e4cd442d9973304f6c4751a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":494,
                  "y":30},
                "size":{
                  "width":87,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83a21ee778c646048318307aa0d86359",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":494,
                      "y":30},
                    "size":{
                      "width":87,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u69.png"}},
{
              "id":"17c5d62acc1d4ccd97fe5879a4db797e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":494,
                  "y":60},
                "size":{
                  "width":87,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ca183cc20034469ab87c8b2055dc0de",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":494,
                      "y":60},
                    "size":{
                      "width":87,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u79.png"}},
{
              "id":"fa1c62346d2a498aa18eb55ab84fe311",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":378,
                  "y":0},
                "size":{
                  "width":116,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b48918efe8d743e9a1df6e6b149b6794",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":378,
                      "y":0},
                    "size":{
                      "width":116,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u57.png"}},
{
              "id":"89f9a89181e04ba791180a24ff69fb84",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":30},
                "size":{
                  "width":116,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97ba7727dd6444559d45b6ef5799a08e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":30},
                    "size":{
                      "width":116,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u67.png"}},
{
              "id":"e5f47d3988284240b5635b163d776c23",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":60},
                "size":{
                  "width":116,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a49a9a5bb03742f0aa5e265e15492746",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":60},
                    "size":{
                      "width":116,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u77.png"}},
{
              "id":"4ff4b0398f7045dbbcc521e857fed713",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":88},
                "size":{
                  "width":126,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8d3068a94fc54968b6fe694b24683c59",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":88},
                    "size":{
                      "width":126,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u71.png"}},
{
              "id":"049c6b63176643849cb694dbe0b86eb4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":88},
                "size":{
                  "width":126,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e19facb9ee0146eaaaf82e29f9b1de95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":88},
                    "size":{
                      "width":126,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u71.png"}},
{
              "id":"5097d5a56cf846dabfc3ba7548dc2a92",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":252,
                  "y":88},
                "size":{
                  "width":126,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9a4069a0fb1741ac964b5498941df996",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":252,
                      "y":88},
                    "size":{
                      "width":126,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u71.png"}},
{
              "id":"fec00ff9a2cf49d59ef8df9c44409e84",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":88},
                "size":{
                  "width":116,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"60f8a911ffa34c50ac37b1e5cd26e3f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":88},
                    "size":{
                      "width":116,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u77.png"}},
{
              "id":"e61f96f8041f4c3a8c1814a2b6a68565",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":494,
                  "y":88},
                "size":{
                  "width":87,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39bc67f74e8545358edee54e9cba3983",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":494,
                      "y":88},
                    "size":{
                      "width":87,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u79.png"}},
{
              "id":"fbb5a4a82aba41719340a6936613eaac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":116},
                "size":{
                  "width":126,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f3b9bd6f76843cfa671240c7a822fe7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":116},
                    "size":{
                      "width":126,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u91.png"}},
{
              "id":"ecdb4f05fcaf4bd49fe0f7d82afcbe70",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":116},
                "size":{
                  "width":126,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5ecd74a7751e4704a7ad968f0032f43b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":116},
                    "size":{
                      "width":126,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u91.png"}},
{
              "id":"859fef3673d04e4a84223b2a3361fd80",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":252,
                  "y":116},
                "size":{
                  "width":126,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bf83a405a22740d3902cfc550d479674",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":252,
                      "y":116},
                    "size":{
                      "width":126,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u91.png"}},
{
              "id":"ce4affc50551482d976da104ffb6a433",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":116},
                "size":{
                  "width":116,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"520b0787e3a24e948949093923e5c9a6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":116},
                    "size":{
                      "width":116,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u97.png"}},
{
              "id":"db30b1c2994f451b824d2e213eb345cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":494,
                  "y":116},
                "size":{
                  "width":87,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd5333d9e40448f6ab0fb095baa2fb73",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":494,
                      "y":116},
                    "size":{
                      "width":87,
                      "height":28}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/门店评价排名/u99.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "03c1666168c94e3baf1d3bfe07423490":{
      "scriptId":"u0"},
    "ff627f7127eb4afb87ab2df30c85a1bd":{
      "scriptId":"u1"},
    "b46407a373914665b508a311f364fb8d":{
      "scriptId":"u2"},
    "d8abc925174c41dd8fd6f814e411cff5":{
      "scriptId":"u3"},
    "0252a9a268be4ef2818280d0717b9ce9":{
      "scriptId":"u4"},
    "e1a4cecc964043958d90ac80512dff73":{
      "scriptId":"u5"},
    "f511c452d4a14dffbe4c0847eddf625d":{
      "scriptId":"u6"},
    "e4e3c5790d0b42c0b001030fb1957b71":{
      "scriptId":"u7"},
    "89525d7147e54c5dbc646879351c7966":{
      "scriptId":"u8"},
    "2003e953eaab478b9d8d70ab743a5247":{
      "scriptId":"u9"},
    "aad78a3a8e8741a2939eafbd5b257208":{
      "scriptId":"u10"},
    "1154c207ed6a488f9598b2fdb9b72373":{
      "scriptId":"u11"},
    "3f7f4fb5082e4988811fc8b4a23851c4":{
      "scriptId":"u12"},
    "1c88e13368e84bbcbed34b0efc9ddd49":{
      "scriptId":"u13"},
    "1c7304ef9d684a2d90cc3f056fa5248c":{
      "scriptId":"u14"},
    "eae9760916f9424c9917598b067074c6":{
      "scriptId":"u15"},
    "ed860859a0a24b1e8f1161c8d549cc71":{
      "scriptId":"u16"},
    "b86996885e3445d58c07b06256ea0921":{
      "scriptId":"u17"},
    "8ca4e3badb92405b8f60f4698388bce7":{
      "scriptId":"u18"},
    "4bc5b73c08db441da45be3fdff6e5471":{
      "scriptId":"u19"},
    "4d2cb1543b524828987bf2d62d9e9caf":{
      "scriptId":"u20"},
    "e9c8fce9811948daa0f207789af7475e":{
      "scriptId":"u21"},
    "c998ed93cbb64e23a970f3ea6ea88915":{
      "scriptId":"u22"},
    "3f37dd473e0449538fb2674829e2b35f":{
      "scriptId":"u23"},
    "cacdd89a528344dfa8058ef91bd846d1":{
      "scriptId":"u24"},
    "7c3ec3da4c834fc4adba428959365fbb":{
      "scriptId":"u25"},
    "d5daf66c73ff4b5b88fb4161a1b6009d":{
      "scriptId":"u26"},
    "8ffb3eb8450d4d33b53b35c5f5425974":{
      "scriptId":"u27"},
    "96f2060315414ec8943fe2e6b11dbc0f":{
      "scriptId":"u28"},
    "d27c5e6343d0416f9a1ff24c5cd07755":{
      "scriptId":"u29"},
    "b57edcd60cdb45808ac39c133eef85de":{
      "scriptId":"u30"},
    "43c3bc78b6284cbd806cc9f40debb658":{
      "scriptId":"u31"},
    "89b019dab1b04cadb3b9a519186fc70b":{
      "scriptId":"u32"},
    "7ff2fccf858348e0892846d382b4a22b":{
      "scriptId":"u33"},
    "dd8eeff987774ec79e928768ccbd9cb7":{
      "scriptId":"u34"},
    "434de672b0bf44639eabacde8cfd3ab3":{
      "scriptId":"u35"},
    "b2df02b8672f4ac39112063cb8770d13":{
      "scriptId":"u36"},
    "d89ee1e4aaf748deba51d948bd82a93b":{
      "scriptId":"u37"},
    "8c186dca97f4419a8dc82135c8a06c87":{
      "scriptId":"u38"},
    "b9d08114d29f43ef9c8270c8391d9375":{
      "scriptId":"u39"},
    "988bbc16994f43a5a9801c799d12121d":{
      "scriptId":"u40"},
    "3db4d053277d4950adc7ecca54e454b0":{
      "scriptId":"u41"},
    "c0742472d40b43a78616f2972fe10445":{
      "scriptId":"u42"},
    "d58ee195d49a4fe1affb4c99fbe76cf0":{
      "scriptId":"u43"},
    "a6f1226af4ea44e48806b7d30249acaa":{
      "scriptId":"u44"},
    "d5ce440aeb924762b6bb943b6514a486":{
      "scriptId":"u45"},
    "26a57ef67c81421f98f42f4580afd175":{
      "scriptId":"u46"},
    "58873b1d017c4ee4b8c8b0743853fa92":{
      "scriptId":"u47"},
    "26eece99fd6d43aca84a3fa6260624e1":{
      "scriptId":"u48"},
    "2aa4020c55d64d4dac57f75ec1363af4":{
      "scriptId":"u49"},
    "7d6331d077654cc2abc6667d7f49a02f":{
      "scriptId":"u50"},
    "9a95354d77194a5599a0ca22364a313b":{
      "scriptId":"u51"},
    "d44b40c525a4470c805a70bfc37477bf":{
      "scriptId":"u52"},
    "22e1d491804f43f998b36efa67c81d81":{
      "scriptId":"u53"},
    "b956d71e78c14ebf8e4070f06dad00c9":{
      "scriptId":"u54"},
    "9959d1614263411e8fae66c1a2a8958f":{
      "scriptId":"u55"},
    "fe591c40b5d6407e97ac166907eeb652":{
      "scriptId":"u56"},
    "fa1c62346d2a498aa18eb55ab84fe311":{
      "scriptId":"u57"},
    "b48918efe8d743e9a1df6e6b149b6794":{
      "scriptId":"u58"},
    "2d087a5c22a247a59909b73e699981ca":{
      "scriptId":"u59"},
    "e8a28c2a84964042a72b2270374fd8b9":{
      "scriptId":"u60"},
    "30ac0854d4514da0b82c21eac98e2bd6":{
      "scriptId":"u61"},
    "52ae2c441d9f41a3947619d3a698a3ce":{
      "scriptId":"u62"},
    "563bbc21a1294c8f8259dcaafbdd56f0":{
      "scriptId":"u63"},
    "e173628104774876b3dc08361d99ed56":{
      "scriptId":"u64"},
    "edd0211e84b84165ae5db69868f562e8":{
      "scriptId":"u65"},
    "a6125e5304e8493c96549fe4b719179e":{
      "scriptId":"u66"},
    "89f9a89181e04ba791180a24ff69fb84":{
      "scriptId":"u67"},
    "97ba7727dd6444559d45b6ef5799a08e":{
      "scriptId":"u68"},
    "9993c352e4cd442d9973304f6c4751a9":{
      "scriptId":"u69"},
    "83a21ee778c646048318307aa0d86359":{
      "scriptId":"u70"},
    "166d808614b5456d9e633b60979a3583":{
      "scriptId":"u71"},
    "4e7fd831086c416caed7412f4b597534":{
      "scriptId":"u72"},
    "e61832b47e1c4cdf979b4aa587ecb8af":{
      "scriptId":"u73"},
    "bf82f1cf05dd4748aaca42b845011c88":{
      "scriptId":"u74"},
    "7a51dd96c67a4326b65637aa45f259cc":{
      "scriptId":"u75"},
    "fc884954d51a4eb2b539fa3fa44299e1":{
      "scriptId":"u76"},
    "e5f47d3988284240b5635b163d776c23":{
      "scriptId":"u77"},
    "a49a9a5bb03742f0aa5e265e15492746":{
      "scriptId":"u78"},
    "17c5d62acc1d4ccd97fe5879a4db797e":{
      "scriptId":"u79"},
    "8ca183cc20034469ab87c8b2055dc0de":{
      "scriptId":"u80"},
    "4ff4b0398f7045dbbcc521e857fed713":{
      "scriptId":"u81"},
    "8d3068a94fc54968b6fe694b24683c59":{
      "scriptId":"u82"},
    "049c6b63176643849cb694dbe0b86eb4":{
      "scriptId":"u83"},
    "e19facb9ee0146eaaaf82e29f9b1de95":{
      "scriptId":"u84"},
    "5097d5a56cf846dabfc3ba7548dc2a92":{
      "scriptId":"u85"},
    "9a4069a0fb1741ac964b5498941df996":{
      "scriptId":"u86"},
    "fec00ff9a2cf49d59ef8df9c44409e84":{
      "scriptId":"u87"},
    "60f8a911ffa34c50ac37b1e5cd26e3f6":{
      "scriptId":"u88"},
    "e61f96f8041f4c3a8c1814a2b6a68565":{
      "scriptId":"u89"},
    "39bc67f74e8545358edee54e9cba3983":{
      "scriptId":"u90"},
    "fbb5a4a82aba41719340a6936613eaac":{
      "scriptId":"u91"},
    "3f3b9bd6f76843cfa671240c7a822fe7":{
      "scriptId":"u92"},
    "ecdb4f05fcaf4bd49fe0f7d82afcbe70":{
      "scriptId":"u93"},
    "5ecd74a7751e4704a7ad968f0032f43b":{
      "scriptId":"u94"},
    "859fef3673d04e4a84223b2a3361fd80":{
      "scriptId":"u95"},
    "bf83a405a22740d3902cfc550d479674":{
      "scriptId":"u96"},
    "ce4affc50551482d976da104ffb6a433":{
      "scriptId":"u97"},
    "520b0787e3a24e948949093923e5c9a6":{
      "scriptId":"u98"},
    "db30b1c2994f451b824d2e213eb345cf":{
      "scriptId":"u99"},
    "dd5333d9e40448f6ab0fb095baa2fb73":{
      "scriptId":"u100"}}});