$axure.loadCurrentPage({
  "url":"项目合作数据.html",
  "generationDate":new Date(1413021311327.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f2825c107cc5475bb92c15b789beab5a",
    "type":"Axure:Page",
    "name":"项目合作数据",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03c1666168c94e3baf1d3bfe07423490",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":970,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff627f7127eb4afb87ab2df30c85a1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":970,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u10.png"}},
{
          "id":"b46407a373914665b508a311f364fb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":0,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8abc925174c41dd8fd6f814e411cff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":0,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"0252a9a268be4ef2818280d0717b9ce9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":100,
              "y":67},
            "size":{
              "width":768,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a4cecc964043958d90ac80512dff73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":100,
                  "y":67},
                "size":{
                  "width":768,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费者评价/u4.png"}},
{
          "id":"f511c452d4a14dffbe4c0847eddf625d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":868,
              "y":67},
            "size":{
              "width":100,
              "height":542},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e3c5790d0b42c0b001030fb1957b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":868,
                  "y":67},
                "size":{
                  "width":100,
                  "height":542},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家登录/u2.png"}},
{
          "id":"89525d7147e54c5dbc646879351c7966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF23BEB1},
            "location":{
              "x":0,
              "y":608},
            "size":{
              "width":970,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2003e953eaab478b9d8d70ab743a5247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1},
                "location":{
                  "x":0,
                  "y":608},
                "size":{
                  "width":970,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u36.png"}},
{
          "id":"aad78a3a8e8741a2939eafbd5b257208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":970,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1154c207ed6a488f9598b2fdb9b72373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":617},
                "size":{
                  "width":970,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请合作/u38.png"}},
{
          "id":"3f7f4fb5082e4988811fc8b4a23851c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c88e13368e84bbcbed34b0efc9ddd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c7304ef9d684a2d90cc3f056fa5248c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae9760916f9424c9917598b067074c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed860859a0a24b1e8f1161c8d549cc71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":444,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86996885e3445d58c07b06256ea0921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":444,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca4e3badb92405b8f60f4698388bce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"16px",
            "location":{
              "x":600,
              "y":629},
            "size":{
              "width":80,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc5b73c08db441da45be3fdff6e5471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"16px",
                "location":{
                  "x":600,
                  "y":629},
                "size":{
                  "width":80,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2cb1543b524828987bf2d62d9e9caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Droid Sans Regular', 'Droid Sans'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":180,
              "y":670},
            "size":{
              "width":730,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c8fce9811948daa0f207789af7475e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Droid Sans Regular', 'Droid Sans'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":670},
                "size":{
                  "width":730,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c998ed93cbb64e23a970f3ea6ea88915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":105},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f37dd473e0449538fb2674829e2b35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":105},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cacdd89a528344dfa8058ef91bd846d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":130},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3ec3da4c834fc4adba428959365fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":130},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5daf66c73ff4b5b88fb4161a1b6009d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":138,
              "y":156},
            "size":{
              "width":80,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffb3eb8450d4d33b53b35c5f5425974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":156},
                "size":{
                  "width":80,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f2060315414ec8943fe2e6b11dbc0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":181},
            "size":{
              "width":90,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d27c5e6343d0416f9a1ff24c5cd07755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":181},
                "size":{
                  "width":90,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b57edcd60cdb45808ac39c133eef85de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF23BEB1,
              "opacity":1},
            "location":{
              "x":138,
              "y":205},
            "size":{
              "width":92,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c3bc78b6284cbd806cc9f40debb658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF23BEB1,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":205},
                "size":{
                  "width":92,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89b019dab1b04cadb3b9a519186fc70b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":231},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff2fccf858348e0892846d382b4a22b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":231},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd8eeff987774ec79e928768ccbd9cb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":255},
            "size":{
              "width":91,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"434de672b0bf44639eabacde8cfd3ab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":255},
                "size":{
                  "width":91,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2df02b8672f4ac39112063cb8770d13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":279},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d89ee1e4aaf748deba51d948bd82a93b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":279},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6f1226af4ea44e48806b7d30249acaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":302},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ce440aeb924762b6bb943b6514a486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":302},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26a57ef67c81421f98f42f4580afd175",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":324},
            "size":{
              "width":89,
              "height":23},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58873b1d017c4ee4b8c8b0743853fa92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":324},
                "size":{
                  "width":89,
                  "height":23},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1705acc70f1e41268999ba8107c0cf21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":105},
            "size":{
              "width":591,
              "height":351}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e098be5f4a5a45b1864f2504cacfc556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":105},
                "size":{
                  "width":591,
                  "height":351}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目合作数据/u42.png"}},
{
          "id":"e9fbd10dfe2945bd8f97d181af7ee79a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":978,
              "y":354},
            "size":{
              "width":130,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da62eb16e0c646229b14558080ffd34a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":978,
                  "y":354},
                "size":{
                  "width":130,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "03c1666168c94e3baf1d3bfe07423490":{
      "scriptId":"u0"},
    "ff627f7127eb4afb87ab2df30c85a1bd":{
      "scriptId":"u1"},
    "b46407a373914665b508a311f364fb8d":{
      "scriptId":"u2"},
    "d8abc925174c41dd8fd6f814e411cff5":{
      "scriptId":"u3"},
    "0252a9a268be4ef2818280d0717b9ce9":{
      "scriptId":"u4"},
    "e1a4cecc964043958d90ac80512dff73":{
      "scriptId":"u5"},
    "f511c452d4a14dffbe4c0847eddf625d":{
      "scriptId":"u6"},
    "e4e3c5790d0b42c0b001030fb1957b71":{
      "scriptId":"u7"},
    "89525d7147e54c5dbc646879351c7966":{
      "scriptId":"u8"},
    "2003e953eaab478b9d8d70ab743a5247":{
      "scriptId":"u9"},
    "aad78a3a8e8741a2939eafbd5b257208":{
      "scriptId":"u10"},
    "1154c207ed6a488f9598b2fdb9b72373":{
      "scriptId":"u11"},
    "3f7f4fb5082e4988811fc8b4a23851c4":{
      "scriptId":"u12"},
    "1c88e13368e84bbcbed34b0efc9ddd49":{
      "scriptId":"u13"},
    "1c7304ef9d684a2d90cc3f056fa5248c":{
      "scriptId":"u14"},
    "eae9760916f9424c9917598b067074c6":{
      "scriptId":"u15"},
    "ed860859a0a24b1e8f1161c8d549cc71":{
      "scriptId":"u16"},
    "b86996885e3445d58c07b06256ea0921":{
      "scriptId":"u17"},
    "8ca4e3badb92405b8f60f4698388bce7":{
      "scriptId":"u18"},
    "4bc5b73c08db441da45be3fdff6e5471":{
      "scriptId":"u19"},
    "4d2cb1543b524828987bf2d62d9e9caf":{
      "scriptId":"u20"},
    "e9c8fce9811948daa0f207789af7475e":{
      "scriptId":"u21"},
    "c998ed93cbb64e23a970f3ea6ea88915":{
      "scriptId":"u22"},
    "3f37dd473e0449538fb2674829e2b35f":{
      "scriptId":"u23"},
    "cacdd89a528344dfa8058ef91bd846d1":{
      "scriptId":"u24"},
    "7c3ec3da4c834fc4adba428959365fbb":{
      "scriptId":"u25"},
    "d5daf66c73ff4b5b88fb4161a1b6009d":{
      "scriptId":"u26"},
    "8ffb3eb8450d4d33b53b35c5f5425974":{
      "scriptId":"u27"},
    "96f2060315414ec8943fe2e6b11dbc0f":{
      "scriptId":"u28"},
    "d27c5e6343d0416f9a1ff24c5cd07755":{
      "scriptId":"u29"},
    "b57edcd60cdb45808ac39c133eef85de":{
      "scriptId":"u30"},
    "43c3bc78b6284cbd806cc9f40debb658":{
      "scriptId":"u31"},
    "89b019dab1b04cadb3b9a519186fc70b":{
      "scriptId":"u32"},
    "7ff2fccf858348e0892846d382b4a22b":{
      "scriptId":"u33"},
    "dd8eeff987774ec79e928768ccbd9cb7":{
      "scriptId":"u34"},
    "434de672b0bf44639eabacde8cfd3ab3":{
      "scriptId":"u35"},
    "b2df02b8672f4ac39112063cb8770d13":{
      "scriptId":"u36"},
    "d89ee1e4aaf748deba51d948bd82a93b":{
      "scriptId":"u37"},
    "a6f1226af4ea44e48806b7d30249acaa":{
      "scriptId":"u38"},
    "d5ce440aeb924762b6bb943b6514a486":{
      "scriptId":"u39"},
    "26a57ef67c81421f98f42f4580afd175":{
      "scriptId":"u40"},
    "58873b1d017c4ee4b8c8b0743853fa92":{
      "scriptId":"u41"},
    "1705acc70f1e41268999ba8107c0cf21":{
      "scriptId":"u42"},
    "e098be5f4a5a45b1864f2504cacfc556":{
      "scriptId":"u43"},
    "e9fbd10dfe2945bd8f97d181af7ee79a":{
      "scriptId":"u44"},
    "da62eb16e0c646229b14558080ffd34a":{
      "scriptId":"u45"}}});